### ISSUE TITLE
Zombie theme room does not respect level difficulty

### ISSUE THREAD

**Issue by vultur-cadens** [NetHack/NetHack#1016]
https://github.com/NetHack/NetHack/commit/ba60bfac25d0dd46b609429f1c5b35cf15fb036d introduces a zombie theme room, but the zombie corpses that then revive do not respect level difficulty.

This is, as far as I can tell, the most likely explanation for things like [a giant zombie on DL4 XL2](https://au.hardfought.org/userdata/c/cathartes/nethack/dumplog/1682803394.nh.html), [an ettin and 2 human zombies at DL3 XL1](https://www.hardfought.org/userdata/p/post163/nethack/dumplog/1682805432.nh.html), and [an ettin and human zombie at DL2 XL1](https://au.hardfought.org/userdata/c/cathartes/nethack/dumplog/1682804703.nh.html) (these happened within the space of an hour!).  This is a big surprise for early-game characters to encounter.

The theme room generation should be modified so that zombie corpses respect level difficulty.

@copperwater on IRC suggested adding a `nh.mon_difficulty()` Lua function (implemented in [this xNetHack commit](https://github.com/copperwater/xnethack/commit/de8e0d8)) so that theme rooms can determine the difficulty of monsters.

**Comment by copperwater** [comment]
Thought of another, less good but useful in other ways, solution too: expose `mkclass()` to the level parser in some way like 
```lua
local species = nh.mkclass('Z')
des.object({ id='corpse', montype=species, buried=true })
```

The reason this is a less good solution is that it will still produce too-difficult zombies because mkclass still occasionally disregards the current level difficulty and selects a monster that is too strong. Merging #253 would address that problem.
