### ISSUE TITLE
in-game encyclopedia suggests that non-living creatures are immune to Medusa's stoning

### ISSUE THREAD

**Issue by g-branden-robinson** [NetHack/NetHack#1018]
"She became a cruel monster of so frightful an aspect that no living thing could behold her without being turned into stone."

A resourceful (because they bothered to read the in-game encyclopedia) player who was not thoroughly spoiled could thus reason that if they polymorphed into a vampire or wraith, they could face Medusa without fear of stoning.

I suggest either (a) making undead monsters immune to Medusa's stoning gaze or (b) editing the encyclopedia entry to strike the word "living".

I leave for another time the question of whether eating the dead Medusa constitutes "beholding" her.

**Comment by loggersviii** [comment]
I'd argue that a player astute enough to come up with a scheme this elaborate would be aware that the encylopedia entry is a quote from a non-nethack related source, and thus shouldn't be taken as a strategy guide. There's lots of quotes from outside sources in encyclopedia entries like this, and I don't think they're ever meant to be taken as advice of what to do in the game. Examples would be the ogre entry saying they are solitary creatures, even when they spawn in packs, or the dragon entry stating that the most dangerous part of a dragon is its tail. It's flavor at best, and I don't believe stuff like this is meant to be taken at face value.

**Comment by pat-rankin** [comment]
Many of the entries are misleading or not relevant to game play.  Think of them as rumors rather than actual documentation.  They're there mainly for atmosphere and also to encourage players to check out their source material.

The second paragraph is an excerpt from a book and shouldn't be modified unless it is a misquote of the original text or that text contains a blatant typo.  The mention of "dungeon" in the first paragraph suggests that it was made up as an intro to the second paragraph.  If so, it ought to be separated from the excerpt by an empty attribution line of " [] ".  I'm hesitant to make such a change based on guesswork though.

Maybe someone will look that up and chime in?  The copyright for Bulfinch's Mythology is long expired and it's available as a free ebook.  I don't know whether the text for it is directly accessible online somewhere.

**Comment by g-branden-robinson** [comment]
Hi Pat,

Sure, you can get Bulfinch's Mythology from Project Gutenberg along with many other fine public domain works.

https://www.gutenberg.org/cache/epub/4928/pg4928.txt

The full context is as follows.  The first paragraph in the NetHack encyclopedia entry indeed seems **not** to be a direct quote.  NH conflates the gorgons and graeae, whereas Bulfinch distinguishes them.  (And I have no idea whence AD&D got its bipedal, bull-headed, poison-gas-breathing gorgons.)

> The Graeae were three sisters who were gray-haired from their
birth, whence their name. The Gorgons were monstrous females with
huge teeth like those of swine, brazen claws, and snaky hair. None
of these beings make much figure in mythology except Medusa, the
Gorgon, whose story we shall next advert to. We mention them
chiefly to introduce an ingenious theory of some modern writers,
namely, that the Gorgons and Graeae were only personifications of
the terrors of the sea, the former denoting the STRONG billows of
the wide open main, and the latter the WHITE-crested waves that
dash against the rocks of the coast. Their names in Greek signify
the above epithets.
> 
> PERSEUS AND MEDUSA
>
> Perseus was the son of Jupiter and Danae. His grandfather
Acrisius, alarmed by an oracle which had told him that his
daughter's child would be the instrument of his death, caused the
mother and child to be shut up in a chest and set adrift on the
sea. The chest floated towards Seriphus, where it was found by a
fisherman who conveyed the mother and infant to Polydectes, the
king of the country, by whom they were treated with kindness. When
Perseus was grown up Polydectes sent him to attempt the conquest
of Medusa, a terrible monster who had laid waste the country. She
was once a beautiful maiden whose hair was her chief glory, but as
she dared to vie in beauty with Minerva, the goddess deprived her
of her charms and changed her beautiful ringlets into hissing
serpents. She became a cruel monster of so frightful an aspect
that no living thing could behold her without being turned into
stone. All around the cavern where she dwelt might be seen the
stony figures of men and animals which had chanced to catch a
glimpse of her and had been petrified with the sight. Perseus,
favored by Minerva and Mercury, the former of whom lent him her
shield and the latter his winged shoes, approached Medusa while
she slept, and taking care not to look directly at her, but guided
by her image reflected in the bright shield which he bore, he cut
off her head and gave it to Minerva, who fixed it in the middle of
her Aegis.

I admit that, more than editorial revision of the NH encyclopedia, I was hoping more to stimulate feature evolution in the direction of stoning immunity being a property of undead creatures.  With wands of undead turning being usable by monsters against players, I envision there being fun possibilities involving player-zombie-wielded cockatrice corpses and other fun possibilities.

**Comment by copperwater** [comment]
Granting stoning resistance to undead monsters would make it too attractive a tactic, in my opinion, to spend most of the endgame permanently polymorphed into a vampire lord (via unchanging, or polymorph + polymorph control and you choose to re-polymorph into a vampire lord whenever a new polymorph kicks in). 

Vampire lord is already a desirable polymorph form because it's pretty strong, lets you wear all your usual armor, doesn't need to eat or breathe, has a life-draining bite, flies, regenerates, and grants 10 extra points of AC naturally. Stacking on extra benefits like immunity to stoning (which would remove one of the few drawbacks of this form - that you cannot attack a cockatrice in melee because you will bite it and stone yourself) seems the wrong way to go about it.

**Comment by g-branden-robinson** [comment]
On the other hand, it could make monster usage of wands of undead turning much more entertaining.

commit d83f1c178b6832d91c95df21a2067f1360dacd7e
Author: PatR <rankin@nethack.org>
Date:   Sat Apr 11 12:34:32 2020 -0700

    refinement of monster use of undead turning
    
    Instead of just picking up wands of undead turning when one or more
    corpses are in hero's inventory, have monsters also pick those up if
    hero has a cockatrice corpse in a carried container.  And instead of
    only zapping such wands (as defensive measure) when hero is wielding
    a cockatrice corpse, also zap them (as offensive measure) if hero is
    carrying any corpse in open inventory.

**Comment by pat-rankin** [comment]
Undead turning against undead creatures is actually a very weak attack.  Having monsters use it against poly'd hero wouldn't add very much, although it could result in them using up wand charges before the hero captures the wand (in the extremely rare cases when they come across one on the floor before the hero finds it).

[Having undead be turned to stone when looking at Medusa doesn't actually contradict the quote.  It states "no living thing can behold her without being turned into stone" but does not say anything about non-living things.]

**Comment by g-branden-robinson** [comment]
> [Having undead be turned to stone when looking at Medusa doesn't actually contradict the quote. It states "no living thing can behold her without being turned into stone" but does not say anything about non-living things.]

Excellent point.  I should have caught that; I'm used to pointing out in online arguments that "All dogs are red." does not imply that "All non-dogs are not red."

That suffices to sink the ticket for me; closing.
