### ISSUE TITLE
Can I disable "Auto-select every relevant item" or bind to another key?

### ISSUE THREAD

**Issue by Xdminsy** [NetHack/NetHack#1065]
When you drop items, take out or put into a container, the game will prompt you to select types first, `A` for "Auto-select every relevant item", `a` for "All types" and `!` for "potions" an so on.

I never use `A`, if I really want to select everything, I can select all types and type `.` to select all items or `,` to select one page.
Maybe someone like using it, I agree. But it seems redundant and of no use to me and some friends I asked.

The most problem is it may harm.
Only one time did I want to put some things into the bag of holding, but I mistyped `a` with `A`, maybe I'm pressing shift inadvertently, and a wand of cancellation is in my oilskin sack, making the bag of holding explode.
Maybe some of you have encountered this too :). It's not a rare situation (in my view).

My friends tell me they avoid using `a` to select all types but choose `?` or `!` etc. to narrow the types.
But in my view, the only reason to avoid using `a` is just to avoid mistyping `A` to mess all the things up. I almost always use `a` without problems, and it has obvious benefits.

I can still use `!` or `?` to select items of certain types in all types list, and the advantage is to save turns.
Say when I encounter a fire monster, fire ant or pyrolisk, I may drop all my potions and scrolls or put into boh, if you don't use `a`, you may need 2 turns to stash different types of items, then some of them may get fire, so it's the necessity to use `a`.
And many times I want to drop or put into a container a lot of items I still like to `a` instead of bothering to choose different types, it's the convenience.

So I'd say the only problem is sometimes one may mistype `a` with `A`, though I hardly take wand of cancellation or bag of tricks in my inventory, it's still a great threat to many players who carry them, and the result of a boh explosion can apparently end a game. Why should they abandon the power of `a` just because prone to mistyping `A`.

If there is an option to totally disable the ability to "Auto-select every relevant item", or provide a way to bind the `A` to another custom key, it'd be much less tragedy :).

I read some code and find in `pickup.c` it's hardcoded the `A` key. It may be chosen without further thinking.
But In the game history, we found this key `A` damages the power of `a` and made some players avoid using `a`, everyone dislikes ending a game by such a mistype.

It's not a player's wrong decisions that do harm which is their own choice and gets the corresponding bad consequence, it is something that just happened accidentally, and the no design and hardcoding of the two keys.
It may happen due to the player's terminal lag, keyboard problem, or just forgetting to release the shift because of the previous action.

So I suggest maybe we should fix this situation at some time.

**Comment by pat-rankin** [comment]
The short answer is no, there's no way to change the selection letter or the behavior of autoselect-all.  Don't despair, the long answer could prove to be useful....

You haven't said whether you're running 3.6.x or to-be-3.7; the behavior of the first menu for menustyle:full has changed.  The period, comma, at-sign, and tilde menu commands only operate on choices b through whatever letter covers the last eligible class; they skip A, a, BUCX, P.  So you could safely use . instead of a; accidentally shifting . won't do anything in that one-page menu.  [A quick test shows that the bulk handling doesn't skip u (for unpaid when in a shop) which seems like a bug.]

That is menu-specific behavior.  A handful of other menus keep their first or last entry out of bulk select and out of 'on' in bulk toggle operations.  The code supports keeping particular entries out of bulk unselect and out of 'off' in bulk toggle too, but I don't think any menus use it; clearing pending choices isn't inhibited.

For either 3.6.x or to-be-3.7, you could switch from menustyle:full to menustyle:partial which skips the class filtering menu and brings up a menu of all items immediately.  Or to menustyle:traditional which skips menus altogether unless you include m as one of the things of interest in its "pick class(es)" prompt to make it behave like menustyle:combination.

Dropping or stashing all potions and all scrolls does not require two turns, you can just pick both classes before moving to the second menu.  3.4.x handled selecting BUCX state plus classes strangely, by choosing items that met either category.  3.6.x changed that to choose items that meet both categories.  (So it used to be that !?C would choose all potions and all scrolls of any bless/curse state and also all known-cursed items for every other class.   These days it chooses cursed potions and cursed scrolls.  But it always allowed you to specify multiple object classes, and once BCUX was added, multiple states for blessed/uncursed/cursed/unknown could be included in a single operation.)

In to-be-3.7, exploding a bag of holding destroys the bag while scattering its contents instead of destroying those too.  But even when it did destroy everything, that did not mean "game over".  Anyone who refrains from a rage-quit will have a more interesting rest-of-game.  [Look at /?quit sometime.]

**Comment by Xdminsy** [comment]
Thank you for your reply, I apologize that I forget I don't need more turns to drop 2 types of items, so it's not a nessecity to use `a` but just for convenience.
I am playing a self-built 3.7 built in March I think, I always use `menustyle:full`.
I tried other menustyle options and find the full is the best and most familiar to me.
The `menustyle:partial` is quite less powerful, I often use `P` to move items just picked up, or `X` to drop items on altar, `u` for dropping a lot of unpaid items, and `C` when I wanna read a scroll of remove curse.So I'd stick to `menustyle:full`

And yes cause I'm playing 3.7, my only 3 or 4 times blowing up my bag of holding don't destroy everything, most of them are still intact. It's still not fun and makes me don't wanna play that game anymore, so I often ascend asap and play next game if that happened, I hardly ever quit a game even in a bad mood. Of course one can still ascend after such a severe mistake, just make the route longer, it reminds me for now often the problem is I carelessly let some water goes into my boh sometimes lol.

But the boh explosion behavior is deliberately designed, so I don't think these need to be changed, it's my duty to take careful treats with bot, "oPoly and other bohs, the less severe result in 3.7 is already great news for me.

In my view I just wanna change the situation someone mistyping `a` with `A` and blowing up the bag of holding.
The boh explosion is deliberate, but in my view, the keys of these two functions are not, so we may change them :)
But my plan is to add an option to the game, whether controlling the keybinding to auto-select all or disabling this feature entirely. But the same is I have to add an option, I don't want to delete this behavior cause many may rely on and are familiar with it.

I don't know if it is acceptable to add an option, I think it's a kinda expensive decision despite the code maybe. I think it should be discussed whether it deserves an option, as a part of another more powerful option (like adding one more options to menustyle), or just not worth changing the current situation.

I'm not familiar with nethack source code, but I checked some code in `files.c` , and I guess If I gonna add the feature, I may need to add one line in `config_line_stmt` and implement a handler, maybe also the in-game settings.

But for now, your suggestion is quite useful, I learned that I could use `,` and `.` in type selection as well, so yes I could choose not to type `a` anymore, and use `,` and `.` instead.
The minor question is `a` is better for me cause it's in the home row and is the same key as the apply key, so say my boh is `s` than my habit keystrokes are `asoa ` to take out and `asia ` to put items in, this is much smoother than `asi, `, or It's just because I'm not that familiar with these two new things to me.

I often put everything into boh immediately after picking up to avoid losing them due to the environment, except unidentified wands and others which blow up boh. The shocking sphere and others damaging inventory items are quite annoying I'd say. There's quite a large amount of such keystrokes in my gameplay.

**Comment by entrez** [comment]
Maybe you are already aware of this since you're playing 3.7, but I've found 'A' to be much more useful since it was changed so the typical filters can be applied to it (which is a 3.7 change).  You can use 'A!?' to automatically stash all your potions and scrolls in a single action, without individually selecting the items.  So it's no longer necessarily a "apply this action on literally every item in inventory" button, you can use it in a much more precise and deliberate way.  Before that change I basically considered it nothing more than a land mine too, but afterwards I began to use it a lot to do things like pick up an entire stack of just-BUC-IDed items from an altar and stash them all in a box with 'AP'.  But I also rarely use 'a' because I find the ability to filter by category more useful most of the time, unless I really want to pick through my entire inventory by hand.

If you want to modify the key for your own game locally I think a minimal patch would be something like this.  This doesn't modify menustyle:traditional; I think the 'A'/'a' behavior is backwards there compared to menustyle:full so it's not as simple as replacing the use of 'A' there (I guess by the time the more modern interface was settled upon, it was already ingrained enough that changing it would have screwed with muscle memory?):
```diff
diff --git a/include/hack.h b/include/hack.h
index aadac06bb..bb34da76c 100644
--- a/include/hack.h
+++ b/include/hack.h
@@ -1277,6 +1277,8 @@ typedef uint32_t mmflags_nht;     /* makemon MM_ flags */
 #define BUCX_TYPES (BUC_ALLBKNOWN | BUC_UNKNOWN)
 #define ALL_TYPES_SELECTED -2
 
+#define CHOOSE_ALL_CHAR   'Z'
+
 /* Flags for oname(), artifact_exists(), artifact_origin() */
 #define ONAME_NO_FLAGS   0U /* none of the below; they apply to artifacts */
 /*                       0x0001U is reserved for 'exists' */
diff --git a/src/do.c b/src/do.c
index ef0ed5377..8231f9241 100644
--- a/src/do.c
+++ b/src/do.c
@@ -932,7 +932,7 @@ menu_drop(int retry)
         for (i = 0; i < n; i++) {
             if (pick_list[i].item.a_int == ALL_TYPES_SELECTED) {
                 all_categories = TRUE;
-            } else if (pick_list[i].item.a_int == 'A') {
+            } else if (pick_list[i].item.a_int == CHOOSE_ALL_CHAR) {
                 drop_everything = autopick = TRUE;
             } else if (pick_list[i].item.a_int == 'P') {
                 justpicked_quan = max(0, pick_list[i].count);
diff --git a/src/pickup.c b/src/pickup.c
index 642a9504e..4284b0bec 100644
--- a/src/pickup.c
+++ b/src/pickup.c
@@ -1216,9 +1216,9 @@ query_category(const char *qstr,      /* query string */
         (void) strkitten(pack, VENOM_CLASS); /* venom is not in inv_order */
 
     if (qflags & CHOOSE_ALL) {
-        invlet = 'A';
+        invlet = CHOOSE_ALL_CHAR;
         any = cg.zeroany;
-        any.a_int = 'A';
+        any.a_int = CHOOSE_ALL_CHAR;
         itemflags = MENU_ITEMFLAGS_SKIPINVERT;
         add_menu(win, &nul_glyphinfo, &any, invlet, 0, ATR_NONE, clr,
                  (qflags & WORN_TYPES) ? "Auto-select every item being worn"
@@ -3068,7 +3068,7 @@ menu_loot(int retry, boolean put_in)
         if (!n)
             return ECMD_OK;
         for (i = 0; i < n; i++) {
-            if (pick_list[i].item.a_int == 'A') {
+            if (pick_list[i].item.a_int == CHOOSE_ALL_CHAR) {
                 loot_everything = autopick = TRUE;
             } else if (put_in && pick_list[i].item.a_int == 'P') {
                 loot_justpicked = TRUE;

```

**Comment by Xdminsy** [comment]
Wow, I am not aware of that, I have never use `A`, as you remind I see it's more useful than I thought, yes I found `A` respect the other filters, saves two keys.
Maybe I could learn to accustom to the feature, and thank your patch, I learned some more code. I may adapt that.

I remember when I carry wand of cancellation that time cause I wanna genoless, and I thought If I can cancel the L it may be great, but later I find their 90 MR are so difficult to cancel, so I never carry the wand of cancellation after that.
And in 3.7 with the help of amulet of flying, it's quite convenient to dip scrolls and potions into moat, so we don't need cancellation to blank things anymore, the wand of cancellation seems far more useless. I never blow up my boh recently.

Thanks your guys suggestions, learnt a lot today :).
But I am slightly worried if there will be newcomers who may mistype a with A and blowing up the boh lol.

**Comment by janne-hmp** [comment]
Just as an idea, an easy fix for the auto-select all problems would be to add a paranoid query to it as follows:
```
 if (ParanoidAutoSelectAll)
       if (yn("All Items Selected", "Are you sure to select all items?") != 'y')
```
where `#define ParanoidAutoSelectAll ((flags.paranoia_bits & PARANOID_AUTOALL) != 0)`
