### ISSUE TITLE
Out-of-depth figurine generation

### ISSUE THREAD

**Issue by Umbire** [NetHack/NetHack#1068]
In the last couple of days playing the current versions on hardfought.org, specifically:

Unix NetHack Version 3.7.0-86 Work-in-progress - last build May 30 2023  11:53:40 (cc98dc9aa62a9957b082a042edf5bd7ec9f632c7,branch:master)

...I have encountered figurines of monsters well below my current dungeon and experience levels:

- A vampire figurine in a shop on DL 4, while I was a Priest definitely below XL 4. I hit a random teleporter that put me in the shop, where I spotted it and decided to uncurse it before it could animate and possibly end my game.
- An elf-lord figurine in a beartrap found on DL 3 as a low-level Tourist - naturally, also likely cursed. Threw it in the Mines and opted to forget about it.

Is there an off chance of this being related somehow to other out-of-depth generation issues?

**Comment by vultur-cadens** [comment]
It looks like this is intentional behavior: "figurines are slightly harder monsters".

https://github.com/NetHack/NetHack/blob/e44a2a973879a1d51b5ea7f874847583e15f50b0/src/mkobj.c#L1018-L1025

This will result in the lower bound of figurine monster difficulty being 5 more than the normal lower bound, and the upper bound being 10 more than the normal upper bound -- that is, figurine monster difficulty will be between `5+(level_difficulty/6)` and `10+(level_difficulty+experience_level)/2` (except in the rare case of there being no available monsters in the range, in which case it picks randomly over all common monsters).

**Comment by Umbire** [comment]
Guess I'll just have to deal then - thanks in any case.
