### ISSUE TITLE
non-portable use of nroff

### ISSUE THREAD

**Issue by g-branden-robinson** [NetHack/NetHack#1153]
Regarding commit 5bf8b3de6b07a2c5fadd0864b8593095b17c6011 ...

Unfortunately `nroff -c -Tascii` is not very portable.  Heirloom doctools _nroff_ (and its ancestor DWB _nroff_) don't support either option.  (Well, they support the `-T` option, but the option argument `ascii` is a mystery to them.)

This might not be a problem.  If you're assuming _groff_ anyway, then I would do this instead.

```
MAN2TXT = $(NHGREP) | nroff -man -Tascii -P -cbou
```

What this does is ensure that no SGR escape sequences are used (`-c`), and overstriking is not used for boldface (`-b`) or underlining/"italics" (`-u`), nor for character composition (`-o`).

If you want GNU _nroff_ to produce plain Jane ASCII, this is the way to get it.  I use it in many of _groff_'s own regression tests.

You furthermore don't need to mess with `col` in that circumstance.  _grotty_(1) explains:

> ... In contrast to the terminal
> output drivers of some other roff implementations, grotty never
> outputs reverse line feeds.  There is therefore no need to filter
> its output through col(1).

We've been aware of the adjustment parity issue for a while, but hadn't heard from any real-world users who seemed to have a problem with it, so I thank you for giving me a use case.  See [Savannah #57836](https://savannah.gnu.org/bugs/?57836).  Of course that's only an idea at present, so it will be approximately forever before NetHack builds can rely upon the feature.

Let me know if/how I can be of assistance.

**Comment by g-branden-robinson** [comment]
> This assumes that the groff options are compatible between
> Linux and macOS implementations of groff.

Mac OS X stayed on _groff_ 1.19.2 (2005) for over a decade (presumably due to _groff_ 1.20 adopting GNU GPLv3), until finally dropping _groff_ altogether for macOS Ventura (2022).

There _has_ been an interface change in that time.  The [`-P` option I advised about is new to _groff_ 1.23.0 (July 2023)](https://git.savannah.gnu.org/cgit/groff.git/tree/NEWS?h=1.23.0#n86).  (I would have mentioned that  in my original report but [forgot that I was the person who put it in](https://git.savannah.gnu.org/cgit/groff.git/commit/?id=dd725dce808dcff643d33f180ed7ac73e32b0760)--it was almost four years ago.  Sorry. :( )

There is a significant number of _groff_ users via Homebrew (enough that we hear from them occasionally via bug reports).  Some of these have upgraded to 1.23.0 via that mechanism.

You could test for support for the `-P` option like this.

```
NROFF_HAS_P_OPTION=yes
echo | /usr/bin/nroff -P > /dev/null 2>&1 || NROFF_HAS_P_OPTION=

if [ test -n "$NROFF_HAS_P_OPTION" ]
then
   # do one thing
else
  # do another
fi
```

`nroff -` is not necessary with any _nroff_ known to me; like many other Bell Labs Unix programs, it reads from the standard input stream by default if not given any operands.

Again, please consider me  a resource for *roff issues.

**Comment by nhmall** [comment]
Follow-up commit c8f4ad9 changes it so that if the Makefile processing determines that _nroff_ is actually _groff_ , the additional options become:
`-Tascii -P -cbou` if _groff_ version is **1.23 or greater**.
or
`-Tascii -cbou` if _groff_ version is less than **1.23**.


That's assuming that _hints/linux.370_  are in use.
For example, on Linux:
`sh sys/unix/setup.sh sys/unix/hints/linux.370`
or
`cd sys/unix ; sh setup.sh hints/linux.370 ; cd ../..`

For example, on macOS:
`sh sys/unix/setup.sh sys/unix/hints/macOS.370`
or
`cd sys/unix ; sh setup.sh hints/macOS.370 ; cd ../..`

**Comment by g-branden-robinson** [comment]
Hi Michael,

It chagrins me to say so but this is going to have problems too.

```
$ /usr/bin/nroff --version
GNU nroff (groff) version 1.22.4
$ echo | /usr/bin/nroff -Tascii -man -cbou
/usr/bin/nroff: invalid option -cbou
```

What the `-P` option new to _groff_ 1.23.0 does is pass itself and the next argument to _groff_(1), the formatter's front end.  That, in turn, passes the `-cbou` option cluster to the postprocessor, _grotty_(1).  (`-P` is meant to suggest "postprocessor".)

(And as it happens, GNU `nroff` does not support option clusters, but [that's something I'd like to fix for _groff_ 1.24](https://savannah.gnu.org/bugs/?64684).)

While you could support 3 different scenarios, (a) a non-_groff_ `nroff`, (b) `nroff` from _groff_ 1.22.4 and earlier, and (c) `nroff` from _groff_ 1.23.0 (or later), it might be simpler to just treat case (b) like case (a) and continue using `col`.

I'm sorry to be the bearer of so much complex news.

Please advise if and how I can be of assistance.

**Comment by nhmall** [comment]
I've got a commit, at the ready, that I think will accomplish the following once the Makefile processing has been done:

1. If _groff_ version is **1.23 or greater**
`nroff -man -Tascii -P -cbou` .

2. If _groff_ version is less than **1.23** :
`nroff -man -Tascii -c | col`

3.  If  non-groff _nroff_:
`nroff -man | col`

@g-branden-robinson: Does that seem like a reasonable result?

Edit: added the `-c` to result 2, since a contrived test was giving me escape sequences for color when I lied to the Makefile and had the outcome be treated like non-_groff_, even though it actually is still _groff_, for the test.  It feels like we may be back rather close to where this all began. I'm striving for working commands for the three scenarios above. My only test environment is actually scenario 1.

**Comment by g-branden-robinson** [comment]
Hi Michael,

That looks good (after your edit), except that I would also add the `-b` option to the `col` calls for both formatters.  That is what converts the overstriking sequences like `b^Hbo^Hol^Hld^Hd` (**bold**) and `_^Hu_^Hn_^Hd_^He_^Hr_^Hl_^Hi_^Hn_^e` (_underline a.k.a. "italics"_) into human-readable text.

Regarding your second update to the comment, the `-c` options to GNU _nroff_ (or _troff_) mean the same thing (disable color); the `-c` option to _grotty_ (the terminal output driver for GNU _troff_, which gets those options after `-P`) means more than that: it means to pretend that the terminal works like a typewriter.  That includes color disablement, but other things, too.  The _grotty_(1) man page attempts to cover these issues.

And I sympathize.  Working around these compatibility issues is a significant pain in the butt.  It's even worse because _nroff_ output was neglected by AT&T in the 1980s.  Many _tbl_ features produce very ugly output on Documenter's Workbench (DWB; AT&T's commercial _troff_ offering) and on its descendant, Heirloom Doctools.

Since these are man pages, I would be remiss if I didn't mention _mandoc_(1), which is actively maintained and renders man pages well.  (Its maintainer, Ingo Schwarze, is also a _groff_ contributor and we are conscientious about not breaking compatibility with each other.)  Its downsides are that you can't rely upon it to be around, and it's no good for converting any other sort of *roff document (like the NetHack Guidebook) to text--its avowed mission is man pages only.

EDIT: I should add that you can simulate case 2 even on your _groff_ 1.23.0 environment by just not passing the `-P -cbou` argument sequence to (GNU) _nroff_.  What it spits out should look exactly like what _groff_ 1.22.4 would produce with the same flags, maybe modulus some cosmetic changes to the _groff_ _man_ package's output and bug fixes to _tbl_(1) rendering.

**Comment by nhmall** [comment]
_Too much good discussion and activity going on for this to remain a closed issue..re-opening._

If I've followed correctly, I think we've arrived here:

1. If _groff_ version is **1.23 or greater**:
`nroff -man -Tascii -P -cbou`

2. If _groff_ version is less than **1.23**:
`nroff -man -Tascii -c | col -b`

3.  If  non-groff _nroff_:
`nroff -man | col -b`

**Comment by g-branden-robinson** [comment]
Yes, this looks good to me.  Just don't let that trailing `.` creep into the actual code in case 1.  If you tell `nroff` to format a directory, it will silently ignore you.  ;-)

**Comment by nhmall** [comment]
> Just don't let that trailing . creep into the actual code in case 1.

I just thought it was a spec on my screen :)
I've edited my previous comment (again) to correct.

**Comment by pat-rankin** [comment]
Just so we don't lose sight of the goal:  we want to include the lowest common denominator (plain text) in .txt files that are included in the source and binary distributions, but end users who build for themselves might want to produce versions of those files that include bold and/or color and so forth.  The Makefiles probably ought to default to the latter but keep it as straightforward as possible to achieve the former since some end users might want to regenerate plain text themselves.

Just a comment about the justification padding "parity" issue.

There are two aspects:  initial parity being different between formatter versions resulting in big diffs when different developers build and check in new copies of 'roff generated output.  That's a pain when the same input produces different output but it could happen for any alternate tools.  Automating their generation on one system was supposed to eliminate that.  Updating that system has resulted in regression but that will work itself out sooner or later.  (Sooner with your assistance.  Thanks!)

The second aspect is that if a change adds or removes an odd number of lines, the parity for the rest of the file will be changed regardless of what it was at the start.  Maybe it could be reset for each N paragraphs or some such to end up back in sync.  Even that can't help with a small change provoking different page breaks and consequently big diffs for minor changes to long documents.  I don't see how to improve that, other than just live with it.  [We used to live with it by manually regenerating the .txt files sporadically rather than automatically for every revision.  Dealing with the first aspect via automation resulted in bigger ramifications than anticipated.]

All in all, maybe not worth spending many cycles fretting over.  [Something that might be more worthwhile:  when inserting padding, rather than splitting the line into words and inserting spaces from left to right or right to left, make up to three passes after the split.  First give priority to inserting after sentence ending punctuation, then if more padding is still needed, give priority after other punctuation, and if still needed, after arbitrary words.  Each pass could operate right-to-left or vice versa or maybe alternate among passes rather than lines.  Perhaps something like that has already been implemented; I'm using an old version and it clearly doesn't behave that way--which I found surprising when I noticed.]

**Comment by g-branden-robinson** [comment]
Hi Pat,

I'll postpone the adjustment parity discussion because it's a distinguishable topic from the matter of portable `nroff` invocation.

> Just so we don't lose sight of the goal: we want to include the lowest common denominator (plain text) in .txt files that are included in the source and binary distributions, but end users who build for themselves might want to produce versions of those files that include bold and/or color and so forth. The Makefiles probably ought to default to the latter

I'm not sure that's necessary.  Both _mandoc_ and _man-db_ are capable of rendering a man page given only a file name (old school Unix _man_(1) commands were not so friendly).  What I term Brouwer/Lucifredi _man_ (since it seems to have no other name) stopped being shipped by Fedora/Red Hat and SuSE over 10 years ago IIRC, and was moribund well before that.  For NetHack players, I would think that leaves what remains of proprietary/commercial Unix, and non-POSIX platforms that probably lack a `man` command altogether.  (**EDIT**: [FreeBSD _man_(1) is a shell script.](https://cgit.freebsd.org/src/tree/usr.bin/man/man.sh)  I _think_ macOS now uses this script, or a fork of it, as of Ventura (2022) but have no access to a box of sufficiently recent vintage to examine the situation myself.)

```
$ MANWIDTH=65 man doc/dlb.6 |less -R
DLB(6)                    Games Manual                   DLB(6)

NAME
     dlb - NetHack data librarian

SYNOPSIS
     dlb { xct } [ vfIC ] arguments...  [ files...  ]

DESCRIPTION
     Dlb is a file archiving tool in the spirit (and tradition)
...snip...
$ mandoc doc/dlb.6 | ul | head
DLB(6)                           Games Manual                           DLB(6)

NAME
       dlb - NetHack data librarian

SYNOPSIS
       dlb { xct } [ vfIC ] arguments...  [ files...  ]

DESCRIPTION
       Dlb is a file archiving tool in the spirit (and tradition) of tar for
```

On the other hand, it looks like some of the man pages, like this one, are not _ready_ for rendering straight from the tree; I see some stuff involving string definitions that, judging by _doc/dlb.txt_, must be getting handled by the Makefile.

This suggests another possibility; ship some `.6.in` files for the man pages, have the Makefile generate `.6` files from them, say by using _sed_(1) to replace `@UNLIKELY_CHARACTER_SEQUENCES@` in the `.in` files, and then boom, upon any build you have man pages ready to read, in the tree or out of it.

And if you still want to preformat plain text versions, you still can.  `.txt` would continue to depend on `.6`.

_groff_ does [something similar](https://git.savannah.gnu.org/cgit/groff.git/tree/Makefile.am?h=1.23.0#n831).  In one place it's a bit more heavyweight; I wanted to generate two man pages, _groff_man_(7) and _groff_man_style_(7) from a single maintained document (to avoid information desync).  I turned to another old classic Unix tool, _m4_, which gave me an excuse to learn it at last.  What I wanted to do would have looked insanely hairy with _sed_ because I would need multi-line replacements.  But _m4_ has its own hazards--you have to be careful to quote certain English words that are part of its own language.  (The ones that reliably blew up in my face were `define` and `include`.)  This would silently corrupt the output, so what I did was [write a Makefile target to catch my own blunders](https://git.savannah.gnu.org/cgit/groff.git/tree/tmac/tmac.am?h=1.23.0#n252).)  So I recommend _sed_ over _m4_ unless you really need an elephant gun.  It's not like _sed_ is weak; it's Turing-complete, so pretty darned powerful, but I've seen its syntax discourage even hard-bitten C programmers.

>  but keep it as straightforward as possible to achieve the former since some end users might want to regenerate plain text themselves.

I'm happy to help, but I have a somewhat dark suspicion that few people read NetHack's man pages in _any_ format.  Or the Guidebook, for that matter... :-/  (That doesn't mean I'm not happy to help improve them.)

**Comment by Rhialto** [comment]
_Some_ versions of m4 have an option to make its keywords less likely to be confused with running text. But then you'd have the portability issues of different versions of m4...
This is from m4(1) on NetBSD 9.3:
```
     -P, --prefix-builtins
             Prefix all built-in macros with `m4_'.  For example, instead of
             writing define, use m4_define.
```

**Comment by g-branden-robinson** [comment]
> _Some_ versions of m4 have an option to make its keywords less likely to be confused with running text. But then you'd have the portability issues of different versions of m4... 

Hi Rhialto,

I'm aware of it.  I didn't want to dig deeply into the issue because I didn't want to make _groff_'s build dependencies tighter for the sake of a man page I was maintaining.  Even though my approach requires one feature that wasn't in Seventh Edition Unix, the `-D` option, we haven't gotten any reports of breakage (and we should have, since an _m4_ not supporting it would crash the build upon failure to open a file named `-D_groff_man_not_style`).

Regards,
Branden

**Comment by g-branden-robinson** [comment]
Hi Pat,

I think all that remains of this is a discussion of adjustment parity.  I have some comments but they're pretty off-topic for this bug, and have much more to do with *roffs past and present than anything directly to do with NetHack.

Do you mind if I add you to the CC list of the aforementioned [Savannah #57836](https://savannah.gnu.org/bugs/?57836) bug?

Regards,
Branden

**Comment by g-branden-robinson** [comment]
@pat-rankin : Ping, re: adjustment parity and "Do you mind if I add you to the CC list of the aforementioned [Savannah #57836](https://savannah.gnu.org/bugs/?57836) bug?"

**Comment by pat-rankin** [comment]
I didn't intend to ignore the previous question, it just worked out that way.  I don't think I have enough interest to become involved in how that bug gets resolved.

I hadn't thought about whether the parity should alternate as usual after a line that didn't need any padding.  Keeping it the same makes sense.  That should be generalized to "a line whether every separation needed the same amount of padding."
