### ISSUE TITLE
Change Filename $(GAME) ?

### ISSUE THREAD

**Issue by JPRuehmann** [NetHack/NetHack#1214]
Hello
I try to make all three Versions (nethack (TTY), Xnethack (X11) and qnethack (QT4)) to install in paralell in /usr/games and /usr/lib/games/nethack/ for Kubuntu 18.04 LTS (32Bit). Therefore I need to use different Names at Compiletime. Seting the GAME=nethack directive to GAME=Xnethack in the Makefile wont help, it still compiles nethack and the Folder nethack.

**Comment by Rhialto** [comment]
You can build all of the user interface versions into one binary. Maybe
that is easier for your case.

For packaging in Pkgsrc
(https://github.com/NetBSD/pkgsrc/tree/trunk/games/nethack-x11 and -tty
and -lib) there are some patches to create different executables. And
there is a change to the wrapper script to choose the correct version.

However I don't like this much, because there are ways to set the UI
that you like which are difficult to find for the script. So it
basically defaults to running the biggest version that has been
installed, hoping that this will work. For the pkgsrc setup it should,
since each "bigger" version also includes all "smaller" ones.

A previous version of the wrapper script even demanded an extra first
argument to specify the desired UI. I liked that even less so I got rid
of it.

The "nethack-lib" package contains the common files, and nethack-tty
resp. nethack-x11 contain only the additional files needed for that UI.

I'm not sure what a good solution would be here.

**Comment by JPRuehmann** [comment]
Thanks,
I´ve have fund a Way to make it work.
On the way I´ve found a problem in the conf.h
All compiled Versons started with the error that they can´t find ```/lib/usr/games/nethackdir`` I´ve set the Path ```/usr/lib/games/nethack``` in the hints File.
The Problem is a Function that sets the Path if it is not set, after changing that and commenting out the Variable GAME in the conf.h and set it in the hints File it works as wished.
The next one would be to change the safe Directory to ~/.config/nethack/safe for the USER that runs the Programm.

**Comment by JPRuehmann** [comment]
By the Way, NCurses only work for the Terminal Version. All othe throw an Error. If it is set via .nethackrc

**Comment by JPRuehmann** [comment]
Found the solution, (make $(GAME)).
