### ISSUE TITLE
Curses and extended command menus

### ISSUE THREAD

**Issue by Umbire** [NetHack/NetHack#1229]
Formally writing this up so it can be properly dealt with (and so paxed can stress out about 10% less) instead of assuming someone else will Eventually take care of it: In 3.7, there seems to be a curses-specific bug that causes the extended command prompt to appear again after performing such a command - this only seems to happen with certain extended commands, and while I can vouch for what's being complained about in some channels, I don't remember the exact commands in question due to not playing 3.7 in a while. I can circle back with some examples later tonight.

**Comment by Umbire** [comment]
Oh wow, blanked on this for an entire week.

To my vague recollection I've had it happen with #dip and #untrap, I think...

**Comment by ars3niy** [comment]
I see this with #dip a lot but not always.

**Comment by ars3niy** [comment]
Actually, it happens with any extended command and can be easily reproduced. Do repeated wait say 3 times (n3s, with numpad movement on), then #sit. After the action is performed, you're in extended command prompt again. Type sit (without the # since you're already in command prompt), same thing. Type sit again, this time you're out of command prompt. The amount of times you need to enter the command before you don't auto-enter command prompt after completing it, including the first time when you did have to enter command prompt explicitly, is exactly equal to the amount of times you have repeat-waited previously.
