### ISSUE TITLE
sitting on cockatrice corpse doesn't petrify

### ISSUE THREAD

**Issue by keplerstelescope** [NetHack/NetHack#1247]
sitting on a cockatrice corpse, even without any worn armor, doesn't petrify the hero, instead just printing "It's not very comfortable..." as with other corpses. this could be intentional, but seems inconsistent with other actions that involve touching the corpse (feeling while blind, kicking, picking up/wielding, throwing upwards and having it land on head, falling while safely wielding, etc.) worn body armor or maybe cloak could prevent stoning, but it seems odd to have sitting never cause it.

**Comment by entrez** [comment]
I feel like if it stones you, that pretty strongly suggests the hero is nude from the waist down, since there needs to be bare skin contact -- it's sort of a longstanding joke that it's not explicit in-game whether or not the hero is wearing pants because there isn't an armor slot for it, but I think that would be a strange implication to have in there so explicitly.

I guess if you really wanted to have your TDTTOE cake and eat it too you could make gloves protect from it and suggest the hero uses her hands to balance/lower herself to the floor when \#sitting, but that also seems like it would be surprising and not intuitive.  So I think the current lack of stoning is probably for the best, and just implies the hero is wearing something like leggings/pants and a tunic even while "naked" without any armor.

**Comment by loggersviii** [comment]
YANI: if you play a nudist character, they aren't wearing pants, so you die if you sit on a chicken corpse

**Comment by keplerstelescope** [comment]
> So I think the current lack of stoning is probably for the best, and just implies the hero is wearing something like leggings/pants and a tunic even while "naked" without any armor.

i was extrapolating off of the fact that the hero is also implicitly not wearing a shirt to start (other than tourists), but i do see your line of reason.

it also brings to mind the question of why a full complement of armor doesn't (potentially just sometimes) protect you from touching a cockatrice corpse while falling; what parts of the body are touching the corpse exactly?

(also, i apologize for being neurotic. i have a lot of time on my hands. :p)

**Comment by jccostello** [comment]
> it also brings to mind the question of why a full complement of armor doesn't (potentially just sometimes) protect you from 
> touching a cockatrice corpse while falling; what parts of the body are touching the corpse exactly?


I was going to suggest that heroes faceplant into the corpse--not unreasonable for a game with Keystone Kops armed with cream pies. But visored helmets would protect against such a situation. Though they don't protect against cream pies, nor should they. Falling on a corpse could be messy, bits of cockatrice gore slipping through the gaps in your armor.

**Comment by jerk-o** [comment]
What if the hero is wearing something like this: https://en.wikipedia.org/wiki/Roman_military_personal_equipment

**Comment by copperwater** [comment]
Note also that if the cockatrice corpse is covered up with a tiny object such as a dart, sitting on the dart won't give any indication that there's even a cockatrice corpse there (and it would be very strange to stone you in such a case even though it's "realistic").
