### ISSUE TITLE
Hero as small mimic can stick to monsters

### ISSUE THREAD

**Issue by Umbire** [NetHack/NetHack#1266]
...despite small mimics being incapable of this normally. Spotted this while documenting mimic stuff for wiki work:

https://github.com/NetHack/NetHack/blob/2ed95119f12c5f04f84f2a9fffd554a540cdb905/src/mhitu.c#L635-L638

This should probably be changed to exclude the small mimic from those cases.

**Comment by vultur-cadens** [comment]
This doesn't say a small mimic can stick.  `boolean sticky = sticks(gy.youmonst.data)` will determine whether you are really sticky based on the defined monster attacks, and the behavior in the function will be controlled by `sticky` (see the next few lines, `if (sticky && !youseeit)`).

A message like `Wait, newt!  That's a small mimic named wizard!` is printed, instead of the monster getting stuck on you.

**Comment by Umbire** [comment]
Weird, commit 121b9e9 seems to indicate otherwise, unless the monster was misremembered as a small mimic rather than a large or giant one at the time of committing (pretty likely). **EDIT:** Proper link now.

**Comment by vultur-cadens** [comment]
I don't see what that commit has to do with heroes polymorphed into small mimics sticking or not.   It looks like that commit is about the appearance of shapechangers imitating mimics.

**Comment by Umbire** [comment]
Oh, _that_ part's because I'm an idiot and got my pastes mixed up while working, and didn't double back to check like I did with the others - remedied that.

**Comment by vultur-cadens** [comment]
I think you reported an issue that was fixed already.  121b9e97224f3096e1d2db99417f96265cfcb224 *was* the fix for this issue.  Adding the `sticky` check inside the `if (youmonst.data->mlet == S_MIMIC...)` block fixed monsters sticking to hero-as-small-mimic, even though the block is still executed for hero-as-small-mimic.

**Comment by Umbire** [comment]
Well, that's embarrassing! Thanks for catching that.
