### ISSUE TITLE
Give Orctown something to make it better

### ISSUE THREAD

**Issue by nrclark** [NetHack/NetHack#127]
Orctown is very depressing for me sometimes. After diving all the way through the mines, I find out that there's no priest, no shops, no nothing - just a really tough level with bunch of orcs that have wands/poison to kill me with.

It's very demoralizing for me as a player - half of the time, I just quit when I get to Orctown.

I'd love to see some addition to Orctown to make it equal to the rest of the towns, or at least a little closer. Maybe give it an artifact payout or something? Or maybe leave one shop and the temple intact. 

Another option could be maybe to place a conditional engraving on the up staircase on the first level of the mines, something to tell players that the town is an Orctown so that they can avoid the dive if the choose.

Thoughts?

**Comment by copperwater** [comment]
The conditional engraving won't work, because the game doesn't know what Minetown variant will generate until it's actually on the Minetown level and generating it.

In my experience, there are two main gripes about Orcish Town: one is that it adds a lot of unpredictability and throws a wrench in strategies like the protection racket that rely on shops and altars; the other is that it's high risk and low reward, with no prizes except a convertable altar.

Based on comments from devteam members I doubt they will address the first one, because disrupting such strategies seemed to be the goal, but there are a number of ways to fix the risk/reward ratio.

In particular, the weird thing flavor-wise is that all the items from the shops and from the peacefuls' inventories are just gone, and there's no particular indication that the orcs carted them off. In xNetHack, the attempted fix for this is just to drop all those peacefuls' inventories in little piles around the town, and also scatter 9 tools, 4 food items, and 6 lighting supplies (according to the ransacked Frontier Town's map) randomly around the town. This effectively gives you all the loot of the level without having to commit murder for it. It's a small increase in risk - the orcs will pick up and use some of the scattered gear - but a huge increase in reward.
