### ISSUE TITLE
The fountain drinking event will curse your two-weaponing weapon, and if you drop the weapon, any items on the floor will be cursed as if they were inventory items.

### ISSUE THREAD

**Issue by karubabu** [NetHack/NetHack#1315]
Expected behavior
Items on the floor should not be affected by "This water's no good!".

Actual behavior
If the weapon you are two-weaponing is cursed by the event "This water's no good!", and you drop the weapon, the item on the floor will also be cursed.

How to reproduce
1.wish a bunch of blessed items, identify them, and place them on the floor (rings are useful because they don't stack).
2.Do twoweaponing and drink a lot of fountains
3.When "no good!" occurs and you drop your weapon, check if the items you got via wish that you left on the floor are cursed

I have successfully reproduced this on `Unix NetHack Version 3.6.7`.
Reddit user vultur-cadens has successfully reproduced this in commit b953625e of 3.7.0.

For a technical explanation, please refer to the comment by reddit user vultur-cadens at the link below.
https://www.reddit.com/r/nethack/comments/1gkc9ub/even_if_you_drop_an_item_before_drinking_from_the/

**Comment by vultur-cadens** [comment]
Linking relevant source code here for reader convenience:

https://github.com/NetHack/NetHack/blob/b953625e5b48ed01ae2b7edecdb14b580622c3f5/src/fountain.c#L325-L329 Fountain effect code iterates through the inventory linked list and calls `curse()`.

https://github.com/NetHack/NetHack/blob/b953625e5b48ed01ae2b7edecdb14b580622c3f5/src/mkobj.c#L1737 `curse()` drops the weapon with `drop_uswapwep()`, which calls `dropx()`, which calls `dropy()`, which calls `dropz()`, which calls `place_object()`.

https://github.com/NetHack/NetHack/blob/b953625e5b48ed01ae2b7edecdb14b580622c3f5/src/mkobj.c#L2284-L2285 `place_object()` modifies the `nobj` pointer to point to a floor object, so the next iteration of the fountain curse loop will start going through the floor objects instead of the rest of your inventory.

**Comment by nhmall** [comment]
Possible fix:
```
diff --git a/src/fountain.c b/src/fountain.c
index 848adfbfb7..d01c6ed0f2 100644
--- a/src/fountain.c
+++ b/src/fountain.c
@@ -315,18 +315,20 @@ drinkfountain(void)
             dowaterdemon();
             break;
         case 24: { /* Maybe curse some items */
-            struct obj *obj;
+            struct obj *obj, *nextobj;
             int buc_changed = 0;

             pline("This water's no good!");
             morehungry(rn1(20, 11));
             exercise(A_CON, FALSE);
             /* this is more severe than rndcurse() */
-            for (obj = gi.invent; obj; obj = obj->nobj)
+            for (obj = gi.invent; obj; obj = nextobj) {
+                nextobj = obj->nobj;
                 if (obj->oclass != COIN_CLASS && !obj->cursed && !rn2(5)) {
                     curse(obj);
                     ++buc_changed;
                 }
+            }
             if (buc_changed)
                 update_inventory();
             break;
```
