### ISSUE TITLE
AD_DRCO isn't being used as intended

### ISSUE THREAD

**Issue by k21971** [NetHack/NetHack#158]
In src/mhitu.c around line 1190 or so, there's this:

`
    case AD_DRST:

        ptmp = A_STR;

        goto dopois;

    case AD_DRDX:

        ptmp = A_DEX;

        goto dopois;

    case AD_DRCO:

        ptmp = A_CON;

    dopois:

        hitmsg(mtmp, mattk);

        if (uncancelled && !rn2(8)) {

            Sprintf(buf, "%s %s", s_suffix(Monnam(mtmp)),

                    mpoisons_subj(mtmp, mattk));

            poisoned(buf, ptmp, mdat->mname, 30, FALSE);

        }

        break;

`
And noticed the 'goto dopois' line was missing for the 'case AD_DRCO' bit. So the only monster in the game that uses AD_DRCO (rabid rat) isn't up to its full attack potential.

Easy fix: just add 'goto dopois' under 'ptmp = A_CON', works like a charm.

**Comment by akolade** [comment]
Wouldn't execution just continue directly from there to the 'dopois' code anyway? A goto isn't really necessary.

**Comment by ostrosablin** [comment]
That's right. C has a switch statement feature - fallthrough. Unless you explicitly place "break" or "goto" - execution just continues into next label.

What you see here is exactly that - because there's no "break" - we will proceed right into dopois label and execute it anyway.

This doesn't works in, e.g. Pascal, but C and C-inspired languages (even Java) all have switch-case fallthrough. Often C programmers use this to do interesting things that would take more lines of code without fallthrough. In this case, it saves just a single line (goto), by using implicit fallthrough instead.

**Comment by copperwater** [comment]
Confirmed via wizard mode that rabid rats' Constitution poison does in fact kick in when they bite you.
