### ISSUE TITLE
Opening magic can repair broken locks on containers.

### ISSUE THREAD

**Issue by AndrioCelos** [NetHack/NetHack#165]
I noticed this while zapping an unknown wand at a large box that had been broken open, and it repaired the lock but left it unlocked. This occurs both with a wand of opening and with the knock spell. I'm not sure whether this is intentional or not.

**Comment by ostrosablin** [comment]
It's intentional. Because closing magic also repairs broken locks, but it leaves containers locked instead.

I can assume, logic is that you can't really lock/unlock a broken lock, so magic repairs it first, then leaves it in appropriate state. Even more - closing magic would even create a locked door, if casted to an empty doorway, and opening magic would repair broken doors.
