### ISSUE TITLE
Some minor bugs and compiler warnings

### ISSUE THREAD

**Issue by copperwater** [NetHack/NetHack#229]
Found by compiling with -Wall and -Wextra.

The case for specially enumerated tools in loot_classify() falls through to the default case.
```c
            case DRUM_OF_EARTHQUAKE:
            case HORN_OF_PLENTY: /* not a musical instrument */
                k = 3; /* instrument or unknown horn of plenty */
            default:
                k = 4; /* 'other' tool */
```

Also, there are some unmarked fallthroughs in mixtype(), which cause a few alchemy recipes to behave as if you had used a unicorn horn. These may or may not be intended, but they're not marked with the usual `/* FALLTHRU */` to declare them intentional.
```c
    switch (o1->otyp) {
    case POT_HEALING:
        switch (o2->otyp) {
        case POT_SPEED:
        case POT_GAIN_LEVEL:
        case POT_GAIN_ENERGY:
            return POT_EXTRA_HEALING;
        }
    case POT_EXTRA_HEALING:
        switch (o2->otyp) {
        case POT_GAIN_LEVEL:
        case POT_GAIN_ENERGY:
            return POT_FULL_HEALING;
        }
    case POT_FULL_HEALING:
        switch (o2->otyp) {
        case POT_GAIN_LEVEL:
        case POT_GAIN_ENERGY:
            return POT_GAIN_ABILITY;
        }
    case UNICORN_HORN:
```

Other things found by compiler warning that aren't bugs but might be worth fixing:
- Several places in invent.c use (signed) chars as array subscripts.
- get_pricing_units() in shk.c doesn't like having an unsigned and a signed operand in `wt = (obj->owt > 0) ? obj->owt : weight(obj);`
- In win/tty/termcap.c, xputc() gets cast to `(int (*)())` twice, which the compiler doesn't like because xputc's actual type is `void (*)(char)`.
- One 'variable set but not used' warning from the tty windowport; six from the curses windowport. As well as several other miscellaneous warnings from both windowports.
- Two potential fallthroughs in dlb_main.c; neither one can actually fall through because xexit() is called, but it would be nice not to have it throw up warnings.

**Comment by nhmall** [comment]
https://github.com/NetHack/NetHack/commit/f11f4de057d0aca3c843825e55a1d783c90705c2
Fix the first part of github issue 229.  sortloot_classify() tries to
group musical instruments separately from other tools, but missing
'break' in a 'switch' prevented that from happening--they were mixed
together.

https://github.com/NetHack/NetHack/commit/c6b7540712edfde8495bd3a41b018aa0d8a1eecc
Another part of github issue 229, mixtype() didn't have either 'break'
or '/*FALLTHRU*/' separating healing from extra healing, extra healing
from full healing, and full healing from unicorn horn.  So dipping
"bad" potions (sickness, confusion, blindness, hallucination) into
healing/extra healing/full healing or vice versa operated the same as
dipping a unicorn horn into the bad potion (producing fruit juice for
sickness and water for the others).  It wasn't clear from the code
whether or not that was intentional.  It actually seems reasonable
(albeit suboptimal use of {plain, extra, full} healing), so continue
to allow it and make the code clear that it's intentional.

https://github.com/NetHack/NetHack/commit/8443f73265c296c551ae26610c5e61ac794021e6
get_pricing_units() returns a long, so use long for intermediate steps
of the calculation.  Part of github issue 229, about mixing signed and
unsigned.

https://github.com/NetHack/NetHack/commit/a9e8348dfad8b1a70c42ff10c49231bd91967476
    no-return usage in dlb_main.c
    More from github issue 229:  mark routines in util/dlb_main.c which
    don't return as such and add some 'break' statements for compilers
    that don't have support for that.

https://github.com/NetHack/NetHack/commit/0d76f68f2c233c18eebf16d6e5f2afce2f7c0726
Another part of github issue 227.  Casting a function pointer when
    passing it to another function is iffy when lying about the return
    type.  tputs() expects a routine which returns int, so give it one.
    Other xputc() usage is equivalent to putchar(), so define xputc()
    with the same function signature as that has.
    
    The tputs() declarations in system.h should probably be changed
    (third argument is a function which takes an int rather than
    unspecified parameters) but I've left them alone.  I made that change
    to tputs() in sys/share/tclib.c though.
    
    NT and MSDOS changes are untested.  tclib.c compiles ok with clang-
    as-gcc on OSX but hasn't been tested with the port that uses it (VMS).

**Comment by copperwater** [comment]
Expounding on one warning from win/tty/wintty.c: braces suggested around
```c
        /* Now we're truncating */
        if (truncation_expected)
            ; /* but we knew in advance */
```
