### ISSUE TITLE
Build process is stopped in lib/lua-5.3.5/src/lua.h on Archlinux.

### ISSUE THREAD

**Issue by FredBezies** [NetHack/NetHack#256]
I am the maintainer of nethack-git package for Archlinux on AUR.

Since Nethack development switched to 3.7 branch, I cannot get build process to work. Here is the error I get:

`make: *** No rule to make target 'lib/lua-5.3.5/src/lua.h', needed by 'lib/lua-5.3.5/src/liblua.a'.  Stop.`
Lua is installed, of course.

`extra/lua 5.3.5-2 [installed]
    Powerful lightweight programming language designed for extending applications`

Any idea? Thanks.

**Comment by k21971** [comment]
Before 'make' or 'make all', you'll need to issue 'make fetch-lua'
https://github.com/NetHack/NetHack/blob/NetHack-3.7/sys/unix/NewInstall.unx

**Comment by FredBezies** [comment]
Ok. Will try this.

Works a little better, but soon after:
`cc -g -O -I../include -DNOTPARMDECL -DDLB -DCOMPRESS=\"/bin/gzip\" -DCOMPRESS_EXTENSION=\".gz\" -DSYSCF -DSYSCF_FILE=\"/var/games/nethack/sysconf\" -DSECURE -DTIMED_DELAY -DHACKDIR=\"/var/games/nethack/\" -DDUMPLOG -DCONFIG_ERROR_SECURE=FALSE -DCURSES_GRAPHICS -c -o unixres.o ../sys/unix/unixres.c
In file included from ../include/hack.h:200,
                 from nhlobj.c:5:
../include/youprop.h:11:10: fatal error: pm.h: No such file or directory
   11 | #include "pm.h"
      |          ^~~~~~
`

**Comment by k21971** [comment]
Did you do 'make spotless' beforehand? You'll want to start over from a clean slate, pm.h is auto-generated.

**Comment by FredBezies** [comment]
Make list:

make spotless
make fetch-Lua
make

-> broken. It worked before nethack 3.7 switch.

**Comment by k21971** [comment]
At this point, I don't know. AFAIK you're doing it correctly, I use the same steps on Ubuntu and it compiled fine. I have a friend who uses archlinux and I know he's successfully compiled 3.7 on it. I've sent the link to this issue to him to review.

**Comment by copperwater** [comment]
Hi, I'm the Arch user K2 mentioned. I got tripped up by the fetch-lua step as well, but after I ran that I haven't had any problems. I don't have any reason to believe Arch itself is the source of the problem.

In the case of the second error, pm.h is a file that just contains a #define list of the various PM_SOME_MONSTER constants. This file was automatically generated by the 'makedefs' utility program in 3.6, but I think the devteam might be trying to get rid of makedefs in 3.7. I don't know whether the nethack-git package is supposed to maintain save stability, but if so you probably want to keep it pointing at the 3.6 branch until 3.7 is stable or released, because it's currently not a stable branch.

There was also an issue recently when the makefile was messed up and running plain 'make' would go to the wrong target instead of 'all' by default. There may have also been changes to the files in sys/unix, so I would try first making spotless, then rerunning sys/unix/setup.sh, then make all. You should only have to run fetch-lua once ever, unless you manually delete the lib/ folder.

**Comment by FredrIQ** [comment]
I use Arch. I previously had a working NetHack-3.6 setup which could be built fine using make.

After switching to NetHack-3.7, I did this:

% cd sys/unix
% sh setup.sh hints/linux
% cd ../../
% make clean # this errored due to no lib/lua-5.3.5/src
% make spotless
% make fetch-lua
% make

The process finished successfully.

**Comment by paxed** [comment]
I'd suggest not switching to 3.7, because it is very much in very early development, will probably break, invalidate savefiles, and so on multiple times with no announcement. Because it is not a release and nowhere near it.

**Comment by FredBezies** [comment]
@paxed I "downgraded" my PKGBUILD by switching it on nethack 3.6 branch. I will try to switch it to nethack 3.7 in june 2020.

Looks like this bug is useless now.

Thanks for the info.
