### ISSUE TITLE
Why doesn't desktop support UTF8graphics?

### ISSUE THREAD

**Issue by alysdexia** [NetHack/NetHack#264]

**Comment by ostrosablin** [comment]
It would be an excellent addition indeed. I personally prefer IBMGraphics, but in order to play with it I have to use filterm at this moment, which essentially converts CP437 into UTF-8, which modern terminals understand.

Anyway, I believe there are some technical issues with UTF-8. For instance, curses windowport renders window borders with DEC ACS, and mixing ACS with UTF-8 is considered to be malformed output. Many terminals would actually reject ACS chars while in UTF-8 mode.

**Comment by bhaak** [comment]
Mixing DEC graphics like characters with UTF-8 works perfectly fine. If you do it by switching to the  DEC Special Character and Line Drawing Set first with "ESC ( 0" and back with "ESC ( B".

This must be used already otherwise playing with the curses UI port would screw up most modern terminals that are set to UTF-8.

But UTF8graphics is on my TODO list. I hope to do it in a way that you can switch between DEC/IBM- and UTF8graphics on a UTF-8 terminal without having to change the character set.

**Comment by ostrosablin** [comment]
Yes, it works with most Linux terminals, but not everywhere, with most notable example being PuTTY, which rejects DEC ACS in UTF-8 mode and only recently (since 0.71) a patch was included, which adds a checkbox to force processing of VT100 line drawing in UTF-8 mode. This is not only example, though, some ttyrec-to-gif converters also can handle UTF-8 chars, but print DEC line drawing characters with regular charset (which was so annoying that it has motivated me to implement my own ttyrec-to-gif converter).

**Comment by nhmall** [comment]
map window support using ENHANCED_SYMBOLS and enhanced1 in symset in 3.7 work-in-progress
