### ISSUE TITLE
Infinite Loop On / i (examine something you're carrying)

### ISSUE THREAD

**Issue by tarsierscripter** [NetHack/NetHack#274]
I tried to examine my scalpel using / i and the game became unresponsive with CPU usage going to 100%. The only way I could get out was to kill NetHack with ctrl-c, losing my game in the process.

Edit: I'm running 3.6.4 on Mac, installed via homebrew.

**Comment by nhmall** [comment]
Attempts by multiple people to reproduce this, as described, on a Mac tty and on Windows tty were unsuccessful. Do you have any additional information that might help?

If it happens again, perhaps you can get a call graph of the running process by following the instructions in here
https://apple.stackexchange.com/questions/272508/how-do-you-get-a-stack-trace-of-a-running-process

**Comment by tarsierscripter** [comment]
I reproduced it and saved a call graph. Does this help?

[nethack hang.txt](https://github.com/NetHack/NetHack/files/4014546/nethack.hang.txt)

**Comment by nhmall** [comment]
Do you happen to have a savefile of a game that will exhibit this that you could attach?
What were your steps to reproduce it?

**Comment by bhaak** [comment]
@tarsierscripter It tells us where it hangs.

But I can't reproduce it.  I started up a healer with the Homebrew 3.6.4 bottle for High Sierra, but / i works as expected.

**Comment by tarsierscripter** [comment]
@nhmall It actually occurs with any new character I start, examining any item with / i.

@bhaak I am on Catalina. Maybe that causes it?

I will try cloning the repo and building it, to see if I can reproduce it on the master branch.

**Comment by nhmall** [comment]
I just reproduced the same hang on Catalina after downloading the homebrew build.

**Comment by tarsierscripter** [comment]
I successfully built branch NetHack-3.7 and tested it on Catalina: no problems.

I switched to the 3.6.4 release tag and built that, tested on Catalina as well. No problems. I even enabled curses (which I've been using) and / i works fine there as well. This hang seems to be specific to the homebrew build.

**Comment by nhmall** [comment]
From what I can tell, the homebrew build seems to have generated some odd code for the tabexpand function where it gets caught in a tight loop between offset 127 and offset 130. The call to memset just preceding that seems unexpected inside that function too. Perhaps a compiler optimization level has gone awry?

    0x108d36768 <+122>: callq  0x108e64964               ; symbol stub for: memset
->  0x108d3676d <+127>: decq   %r14
    0x108d36770 <+130>: jne    0x108d3676d               ; <+127>

       r14 = 0xffffff2d94f5b933

**Comment by Rhialto** [comment]
I've been playing around a bit with the code on [godbolt](https://godbolt.org/z/oXQyr5) but could not reproduce the bad code. But of course it would probably need the exact compiler version and options that are used in homebrew.

The code might be "miscompiled" due to some undefined behaviour, because the code could be incorrect. But apart from the commented lack of bounds checking, I don't see it (yet?). Or gcc might think that it is detecting the body of some standard function and replacing it with a call to it. But that all depends on optimization settings.

**Comment by nhmall** [comment]
Here are the disassembled tabexpand functions.
First, the one that hangs from the homebrew bottle:
[tabexpand-homebrew.txt](https://github.com/NetHack/NetHack/files/4016663/tabexpand-homebrew.txt)

Next, one just built:
[tabexpand-built-myself.txt](https://github.com/NetHack/NetHack/files/4016664/tabexpand-built-myself.txt)

**Comment by nhmall** [comment]
@Rhialto Thanks for the link. 

I tinkered with it a bit and the code from:
x86-64 clang 8.0.0 -O4 -Os
looks to be a very close match. It has the "callq memset", followed by 
        decq    %rbp
        jne     .LBB0_6

https://godbolt.org/z/5h6cUT

**Comment by Rhialto** [comment]
@nhmall Nice find! I had not remembered that Apple uses clang.

The call to `memset(bp, ' ' ,something)` can be ok of course: it replaces the loop
```
            do  
                *bp++ = ' ';
            while (++idx % 8);
```
and as long as it pre-calculates correctly how often the loop runs, all is well. (Although I don't quickly see how it calculates that).

Since clang 9.0.0 generates different code for the infinite loop (it checks some condition in it now, so it may indeed terminate; but it is still a weird loop, since the C code has no decrement in sight, and anyway the end result is that two registers are equal, which is easier to achieve if that really is what you want),
```
        callq   memset
        notq    %rbp
        xorl    %eax, %eax
.LBB0_6:                                #   Parent Loop BB0_2 Depth=1
                                        # =>  This Inner Loop Header: Depth=2
        #DEBUG_VALUE: tabexpand:idx <- $r15d
        #DEBUG_VALUE: tabexpand:bp <- $r12
        #DEBUG_VALUE: tabexpand:s <- $r13
        #DEBUG_VALUE: tabexpand:sbuf <- $r14
        #DEBUG_VALUE: tabexpand:bp <- undef
        #DEBUG_VALUE: tabexpand:idx <- undef
        #DEBUG_VALUE: tabexpand:bp <- [DW_OP_plus_uconst 1, DW_OP_stack_value] undef
        #DEBUG_VALUE: tabexpand:idx <- [DW_OP_plus_uconst 1, DW_OP_stack_value] undef
        decq    %rax
        cmpq    %rax, %rbp
        jne     .LBB0_6
```
I suspect a compiler bug here in clang 8, which is somewhat improved in clang 9. There might be some appropriate clang mailing list to inquire about that.

**Comment by nhmall** [comment]
@tarsierscripter I see that a new Catalina bottle is now available and the errant optimized code is not present in that one. A quick test of it does not hang  on /i.  

Summary: 
The issue was caused by clang 8 (id'd as clang 11 on Mac OS X) generated code using -Os for the tabexpand function in hacklib.c.

Resolution:
A PR was provided to homebrew by @tarsierscripter to disable the optimizer. The PR was accepted by homebrew and a new revision of the bottle, which became available on January 3, 2020,  does not exhibit the issue. 

Note: The distributed NetHack sources do not include the  optimization setting that generates the errant code in the provided Makefiles and sys/unix/hints/macosx10.14.

I think this issue can be closed now.

**Comment by tarsierscripter** [comment]
@nhmall Yes, I've been testing it and it works fine on my end as well. The issue is resolved.

**Comment by nhmall** [comment]
Note to homebrew users: 

**Make backup copies of your saved games** before doing
_brew upgrade nethack_
to  obtain the new revision that does not have the hanging code.  

You can put the backup copies of your saved games back afterwards, but you will likely lose any games in progress without taking the above precaution first.

**Comment by bhaak** [comment]
Note that the fixed version installs into a new directory.

So if you have a save game, you need to copy it from the old installation to the new.

```
cp /usr/local/Cellar/nethack/3.6.4/libexec/save/* /usr/local/Cellar/nethack/3.6.4_1/libexec/save
```
