### ISSUE TITLE
Segfault when role is randomized

### ISSUE THREAD

**Issue by adn770** [NetHack/NetHack#309]
I believe that at [1] it should be `rn2(n-1)`. I'm reproducing random segfaults at [2] with flags.initrole = 13 that was set at [3]. 

Running step by step on gdb I'd observed n being 14 so it allows for a result of rn2 of 13.

[1] https://github.com/NetHack/NetHack/blob/cca2bcaa84918750eb934bbaf46f5c3120721b6b/src/role.c#L758

[2] https://github.com/NetHack/NetHack/blob/cca2bcaa84918750eb934bbaf46f5c3120721b6b/src/role.c#L1970

[3]
https://github.com/NetHack/NetHack/blob/cca2bcaa84918750eb934bbaf46f5c3120721b6b/src/role.c#L1965

**Comment by copperwater** [comment]
This seems like it could be due to randrole_filtered looping up to SIZE(roles) (which is 14, because of the array terminator) rather than NUM_ROLES (13). It looks like calling ok_role and the rest of those functions with an out-of-bounds role index will treat it as "random" and let it slide through the checks. In which case, n can become 14, flags.initrole can be 13, and the segfault happens.

The fix doesn't involve changing to rn2(n-1), as that would trigger rn2(0) calls for instance when n = 1. It would instead be to not use SIZE(roles).

**Comment by adn770** [comment]
Maybe loop for SIZE(roles) - 1 like in https://github.com/NetHack/NetHack/blob/cca2bcaa84918750eb934bbaf46f5c3120721b6b/src/role.c#L1015 ?

**Comment by nhmall** [comment]
ffcd471ef7e9737032fa7fe85f67cbfdbaca
