### ISSUE TITLE
panic u_on_newpos

### ISSUE THREAD

**Issue by k21971** [NetHack/NetHack#311]
Had a player report a game crash with the following:

_Suddenly the dungeon collapses.
u_on_newpos: trying to place hero off map <80,0>_

Panic log shows the same. This is 3.7.0 edit level 16 as of commit 452962a.

**Comment by copperwater** [comment]
This has happened to a few more players. Specifically we've noticed this on a flipped Castle level; I don't know whether the report by K2 also comes from there.

The cause is because when the Castle gets flipped left-to-right, its sstairs.sx gets flipped from 0 to 80. Then, u_on_sstairs() incorrectly concludes that since sstairs.sx is nonzero, there is an existing set of branch stairs at (80,0), and tries to place the hero there directly with u_on_newpos.

**Comment by k21971** [comment]
We've also now seen a couple reports of monsters embedded in the walls of special levels in gehennom that were flipped.
