### ISSUE TITLE
Relevant commits for CVE-2020-5254/GHSA-2ch6-6r8h-m2p9

### ISSUE THREAD

**Issue by utkarsh2102** [NetHack/NetHack#312]
Hi there,

Thank you for your amazing work on NetHack so far! \o/
However, like [CVE-2020-5253/GHSA-2c7p-3fj4-223m](https://github.com/NetHack/NetHack/security/advisories/GHSA-2c7p-3fj4-223m) lists the commit that fixes that CVE, I couldn't find any particular commits for [CVE-2020-5254/GHSA-2ch6-6r8h-m2p9](https://github.com/NetHack/NetHack/security/advisories/GHSA-2ch6-6r8h-m2p9).

Highly likely I'm missing something, could you please point me to the relevant commits for the same?

**Comment by moon-chilled** [comment]
Look on the NetHack-3.6 branch.

**Comment by carnil** [comment]
> Look on the NetHack-3.6 branch.

More specifically, the issue looks to have been introduced in 3.6.1
(around f8211f69f2008609b59fe4c9ba341ff1fa520825) and then fixed in
abdd3254ae06dd1fbcff637c4c631783d5ed9741 in 3.6.6, is this correct? (This matches as well the range specified in https://github.com/NetHack/NetHack/security/advisories/GHSA-2ch6-6r8h-m2p9)

**Comment by nhmall** [comment]
```
git diff 514682730773318f68d5b28b0428cfe333f92fe0 36ee1849b1932d72a2340233c57701b1274c90ee
```
