### ISSUE TITLE
Deja vu messages appear on non-bones floors with randomly named ghosts.

### ISSUE THREAD

**Issue by AndrioCelos** [NetHack/NetHack#322]
The change to amnesia made it so that you no longer forget maps, so deja vu messages can no longer appear in this case. Instead, these messages now appear when you enter a level containing a ghost whose name matches your own. It seems like this was intended to be seen on the player's own bones floors, but it also happens on levels with randomly named ghosts that choose the player character's name from the high score list (such as Moloch's Sanctum which cannot have bones, and you may not have 'been here before').

The message also would not appear on a bones floor without a ghost, such as if the character was petrified or turned into a wraith.

**Comment by copperwater** [comment]
Perhaps rather than seeing if there is a ghost with the player's name, it should instead check the names stored in the level.bonesinfo list (and if level.bonesinfo doesn't exist, meaning it's a non-bones floor, then no message). This would also account for the case you mention where a bones file is saved but no ghost is created.
