### ISSUE TITLE
Pets become stuck within a shop

### ISSUE THREAD

**Issue by k21971** [NetHack/NetHack#329]
Have had several reports from multiple players of their pets freezing/becoming stuck either inside a shop or at the threshold. Most reports state that a mimic is in the shop, and the pet will be frozen a couple tile spaces away from it. The pet can still do things (picking up/dropping objects), it just won't move from the spot it gets stuck in.

I have a few saves from our 370-hdf build I can share if necessary.

Also, please see this reddit thread - https://www.reddit.com/r/nethack/comments/g13uy3/pets_freezing_in_place/

**Comment by ostrosablin** [comment]
Happened to me today as well (in my case, two dogs at once got stuck).

Not sure if it's related, but there were two mimics disguised as strange objects.

Dogs were undisplaceable and stuck on single square, picking up and dropping objects under them. But as I've hit and awakened both mimics - dogs suddenly un-stucked and began to follow me as usual.

I also suppose it might be related to c8fb419a2c1e71432b876c107e58ec6084aaa979. It's pretty consistent with newly added `return 3;` lines. Dog appears to be stuck in state, when it didn't move and probably can't do anything. It can't attack mimics because they're disguised (but it feels like dogs are aware about their presence) and it can't move for some reason. So I guess, they just stay in one spot, until mimics awaken.

**Comment by tmp6154** [comment]
This if clause in m_move is shop-related and it now triggers due `return 3;` statements from above commit. Not sure, but might be somehow related.

https://github.com/NetHack/NetHack/blob/c8fb419a2c1e71432b876c107e58ec6084aaa979/src/monmove.c#L1534

**Comment by copperwater** [comment]
I've done some sleuthing on a file that was displaying this pet behavior. I think the culprit is in dog_move in dogmove.c: 
```c
        /* Identify the best target in a straight line from the pet;
         * if there is such a target, we'll let the pet attempt an
         * attack.
         */
        mtarg = best_target(mtmp);

        /* Hungry pets are unlikely to use breath/spit attacks */
        if (mtarg && (!hungry || !rn2(5))) {
            int mstatus;

            if (mtarg == &g.youmonst) {
                if (mattacku(mtmp))
                    return 2;
            } else {
                mstatus = mattackm(mtmp, mtarg);

                /* Shouldn't happen, really */
                if (mstatus & MM_AGR_DIED)
                    return 2;

                /* Allow the targeted nasty to strike back - if
                 * the targeted beast doesn't have a ranged attack,
                 * nothing will happen.
                 */
                if ((mstatus & MM_HIT) && !(mstatus & MM_DEF_DIED)
                    && rn2(4) && mtarg != &g.youmonst) {

                    /* Can monster see? If it can, it can retaliate
                     * even if the pet is invisible, since it'll see
                     * the direction from which the ranged attack came;
                     * if it's blind or unseeing, it can't retaliate
                     */
                    if (mtarg->mcansee && haseyes(mtarg->data)) {
                        mstatus = mattackm(mtarg, mtmp);
                        if (mstatus & MM_DEF_DIED)
                            return 2;
                    }
                }
            }
            return 3;
```
In this particular file, the pet, a kitten, was frozen in place in the space just inside the doorway of a shop. There was a cloaked mimic 2 squares exactly north of it. According to gdb, best_target returns the mimic as the best ranged target. Obviously, the kitten doesn't have any ranged attacks, and the mstatus returned from mattackm is 0 (MM_MISS). This will not trigger any of the further if statements, but it will then hit the return 3 (meaning: didn't move, and can't do anything else either). Since it will follow this logic every turn (this ranged attack decision code comes before it actually gets a chance to move adjacent) it ends up being frozen in place except for picking up and dropping items. 

There's nothing special about it being at the doorway of the shop; I was able to reproduce this behavior with pets in other places inside the shop - they also got stuck 2 squares away from the mimic in a line. Likewise, the behavior where the player can't displace the frozen pet inside a shop is also normal; you're not allowed to displace pets at all inside a tended shop.

The special thing about mimics that causes this is that they're the only type of monsters that remains in place doing nothing on their own, while not having a leading passive attack that would cause score_targ not to select them.

Ultimately, I think the root of the problem is that mattackm doesn't distinguish between "made an attack and missed" and "didn't make an attack for whatever reason". Letting the pet move if the result of mattackm is MM_MISS isn't the correct solution; otherwise pets with ranged attacks would be able to attack, miss, then move again. This particular issue could probably be fixed by adjusting score_targ to account for cloaked mimics, but that isn't a very robust solution.

**Comment by AndrioCelos** [comment]
That would explain why closing the door frees the pet, but I believe pets may also get stuck when there isn't a mimic present.

**Comment by copperwater** [comment]
Another variant of this bug was just exposed: a monster stuck in an iron bars closet will trap a pet on the square opposite the iron bars from them (until the monster in the closet dies or gets to move). It mainly just establishes that the targeted monster doesn't need to have something inherent that causes it to stay there unmoving: a monster that can move, but fails to because it's pinned down in one space, works too.

**Comment by k21971** [comment]
See commit 3e0c0f6
