### ISSUE TITLE
Out-of-depth purple liches can appear on any normal level in the Dungeons.

### ISSUE THREAD

**Issue by AndrioCelos** [NetHack/NetHack#349]
There has been a lot of concern about the mausoleum themed room, as it has a chance to generate a monster in the cell, and there's a chance this monster may be an out-of-depth master lich or arch-lich. The monster would quickly warp out to meet the player and quite possibly kill them quickly, theoretically possible on the first floor.

It may be worth changing the themed room so that the monster may be specifically a lich or (maybe) demilich, instead of a random `L`; they aren't covetous and so are much less of an issue. Alternatively, exclude liches altogether while allowing other undead.

As long as demiliches are out of depth, the math seems to work out as follows:

* Each mausoleum has a 7 in 768 chance of getting a master lich, and a 1 in 256 chance for an arch-lich.
* There is an approximately 1 in 79000 chance for any given room to be a purple L mausoleum.
* Assuming 150 rooms in the dungeon, there is an approximately 1 in 500 chance to encounter one somewhere.

**Comment by copperwater** [comment]
See also #344, dealing with other "too hard for early floors" themed rooms, though I strongly believe that it's not the correct solution for this particular problem, because master and arch-liches aren't ever supposed to generate outside Gehennom.

Pull request #253 would, however, fix this problem (by only allowing in-difficulty L to generate) as well as preventing some other cases of purple L generation, such as a gnome stepping on a polymorph trap.
