### ISSUE TITLE
make -j install fails sometimes over contention with grep.tmp file

### ISSUE THREAD

**Issue by amateurhourrrr** [NetHack/NetHack#391]
If I `make clean` followed by `make -j install` I can trigger this for roughly 1/4 compiles. Performing a subsequent `make install` or `make -j install` works correctly after that

The failure message each time is `Can't open '../dat/grep.tmp'.`

I wonder if using something like `mkstemp` would be sufficient to prevent this occurring instead of sharing the same filename for each run

**Comment by copperwater** [comment]
Further information (we were talking about this on IRC): I suspect this is happening because `make -j` allows different build steps to be performed in parallel, so long as they don't depend on each other. So a bunch of commands like `makedefs -r`, `makedefs -h`, and `makedefs -s` all happen at once. Since they all try to do things with the "grep.tmp" file, this could lead to a race condition where one process deletes the file while another process assumes it's created the file and it will still be there when it looks for it again.

I like the mkstemp idea.

**Comment by pillowtrucker** [comment]
is this fixed in 3.6.7 ? I'm having the same problem building with nix right now.
