### ISSUE TITLE
Gelatinous cube can eat too many things in one turn.

### ISSUE THREAD

**Issue by Dev-XYS** [NetHack/NetHack#392]
I was doing altar farming, and as a result there are pages of junk items on the altar. Then a gelatinous cube stepped on it and ate everything on the altar in a single turn. I wonder if it is intentional or is a potential bug.

**Comment by bryceco** [comment]
Sounds like a reasonable outcome to me.

**Comment by copperwater** [comment]
I'd guess neither intentional nor a bug - it's the sort of emergent behavior where the original designer of gelcube eating might not have considered you might have a giant pile of organic items all on one space. Not a bug, since there isn't an obvious problem - the cube is doing what it does, eating organics off the floor.

But since it might not be intended behavior either, there's some chance the devteam would take a pull request that makes cubes not immediately destroy a large pile of organics.

**Comment by pat-rankin** [comment]
Not a bug.
