### ISSUE TITLE
wasm build bugs

### ISSUE THREAD

**Issue by apowers313** [NetHack/NetHack#398]
Thanks for merging #385 :)

The refactoring of the build introduced some wasm build issues:
1. Lua is a required dependency but compiles for the host platform and not the target. It still links and runs (after solving the other issues mentioned below), so I'm confused as to whether the problem is that it shouldn't be building lua or not.
2. The initial build fails with "can't open bogusmon". If I `cd dat && make` then the rest of the build will complete successfully. I'm not sure if this is because of a broken dependency for dlb / nodlb.
3. `libnethack.c` won't compile until `#include "date.h"` is removed. I think that's my bad, but I don't know how it was working before.
4. The application crashes after it is built. I suspect that it's because the build flags are different (e.g. -DNOMAIL, -DSECURE, -DNOSIGNAL)

If someone can give me some hints on how to solve 1 & 2 and recommendations of where to add build flags for 4 (`cross-pre.2020`?), I can put together a pull request. :)

**Comment by nhmall** [comment]
Hopefully, the  build is improved after 3e399848771d4d525b81ab57c4905d9ba3580f6c.

The hints mechanism, in general, results in a src/Makefile stitched together from the following, in this order:
    a) the PRE portion of the specified hints file (including any -INCLUDE files)
    b) sys/unix/Makefile.src
    c) the POST portion of the specified hints file (including any -INCLUDE files)

The PRE portion of sys/unix/hints/linux.2020 and sys/unix/hints/macOS.2020 pull in the following bits common to both via "-INCLUDE" lines:
    sys/unix/hints/include/multiw-1.2020
    sys/unix/hints/include/multiw-2.2020
    sys/unix/hints/include/cross-pre.2020

and the POST portion of sys/unix/hints/linux.2020 and sys/unix/hints/macOS.2020 pulls in the following bits common to both via "-INCLUDE" lines:
    sys/unix/hints/include/cross-post.2020

The variables for various cross-compiles are in sys/unix/hints/include/cross-pre.2020, via override directives so that the standard sys/unix/Makefile.src Makefile portion (which follows the hints PRE portion) cannot alter the value of the things that were set up for the cross-compile. 

The wasm overrides, specifically, are within
`ifdef CROSS_TO_WASM`
`endif`
blocks in sys/unix/hints/include/cross-pre.2020 (which _precedes_ the sys/unix/Makefile.src portion).

The target rules and dependencies for wasm are within 
`ifdef CROSS_TO_WASM`
`endif`
blocks in sys/unix/hints/include/cross-post.2020 (which _follows_ the sys/unix/Makefile.src portion).

**Comment by nhmall** [comment]
For 1:
All of the cross-compile recipes were building the host lua library due to the way dependencies were done in sys/unix/Makefile.top. That will be fixed later today (Sunday Oct 11, 2020).
A target-side lua library is built in targets/{target}/lua540.a during a CROSSCOMPILE_TARGET build, and that is what is included in the link for cross-compiles.

For 2: "The initial build fails with 'can't open bogusmon'. "
The ALLDEP override in the cross-compile recipe should now have the top dependency order improved.  Because the nhdat stuff needs to be embedded during the WASM "link", all of that stuff needed to precede the wasm target.

For 3: libnethack[main].c has been renamed to just libnhmain.c now. The include for "date.h" has been removed.

For 4:  "The application crashes after it is built. I suspect that it's because the build flags are different (e.g. -DNOMAIL, -DSECURE, -DNOSIGNAL)"
Is this still the case?  I attempted to resolve, but I wasn't sure if you wanted -DNOMAIL -DSECURE -DNOSIGNAL there, or you wanted them all removed. Please let me know.
