### ISSUE TITLE
You can get stuck to a mimic by hitting it distantly with a polearm and uncloaking it

### ISSUE THREAD

**Issue by copperwater** [NetHack/NetHack#408]
This happened to me in TNNT: I saw a `]` in a shop, hit it with my polearm and got the "Wait! That's a large mimic!" message (which evidently doesn't do any damage even though I explicitly wanted to hit it, which is a separate problem).

Then it moved next to me, and I attempted to retreat so I could continue using the polearm. But instead, I could not escape from the large mimic, even though neither of us actually hit the other in direct melee combat.

Reproduced this in vanilla wizard mode. It looks like this is because stumble_onto_mimic unconditionally sets u.ustuck to the mimic even if the hero is not next to it. If you attempt to move away when the mimic is still not adjacent to you, it apparently clears this silently and you are free to continue moving; but if you allow the mimic to move adjacent to you, u.ustuck remains set and suddenly the mimic is holding you. (If you uncloak the mimic with the polearm and then zap probing at it while it's still two squares away, it shows up as "holding you" as well.)

**Comment by AndrioCelos** [comment]
Note that it is intentional that actually stumbling onto a mimic sticks you to it even before it hits you.

I notice that pounding calls `attack_checks`, which calls `stumble_onto_mimic`. Perhaps this should be changed in the same way that kicking works, setting `g.context.forcefight` when attacking a hidden hostile monster.

https://github.com/NetHack/NetHack/blob/48fa4fa5dd47e41e6e42bd7d7f04e452dc43640d/src/dokick.c#L130-L131
