### ISSUE TITLE
NetHackJS repo ownership

### ISSUE THREAD

**Issue by apowers313** [NetHack/NetHack#413]
If I [transfer ownership](https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/transferring-a-repository) of the [NetHackJS](https://github.com/apowers313/NetHackJS) repo to  the NetHack organization, can you guys make me a contributor on it? That way if I get hit by a bus, there's no issues around access or control of the repo? And at the same time I can keep adding features to the NetHackJS package?

**Comment by bryceco** [comment]
The issue here is whether the NH team wants to take responsibility for the code and what ownership implies (responding to bug reports etc.). I seriously doubt that the owners of a legacy C code base (not even ANSI C!) want to take on the entirely different responsibilities of a JS port. I recommend you GPL the code so anyone interested in the future can fork it and carry on where you've left off.

**Comment by apowers313** [comment]
I suppose that’s fair, I wasn’t thinking about the skillset needed for maintenance — only the ownership and control. I’ll close this out for now, but I will stand by my offer to transfer it over if the NetHack team ever changes their minds. :)
