### ISSUE TITLE
Special commands listed in the guidebook cannot be rebound

### ISSUE THREAD

**Issue by Luxidream** [NetHack/NetHack#426]
While rebinding extended commands functions normally, trying to rebind a special command like "fight" or "redraw" fails, unbinding the original key without assigning the new one. For example, BIND=v:repeat removes the binding for ^A, but pressing v still gives shortened version information.

**Comment by entrez** [comment]
Discussion on \#hardfought found that it's impossible to rebind 'repeat' because because `DOAGAIN` is used directly instead of `g.Cmd.spkeys[DOAGAIN]` here:
https://github.com/NetHack/NetHack/blob/ae23330adc476a04e031644ee7e7398a6bc9b63d/src/cmd.c#L3367-L3372
Other special commands that resist \[re\]binding are probably similar cases where `g.Cmd.spkeys` (or `ch2spkeys`) should be used instead of a direct comparison to the definition in config.h.
