### ISSUE TITLE
Peaceful monsters that cannot be displaced can be made to flee by attempting to displace them

### ISSUE THREAD

**Issue by Luxidream** [NetHack/NetHack#431]
When you attempt to displace a monster that cannot be displaced, such an aligned priest or quest leader, there is still a 1/7 chance of failing to displace them and scaring them. https://github.com/NetHack/NetHack/blob/0c3b9642e4207ed3c0b756585b83477f59116305/src/uhitm.c#L350 This is problematic for aligned priests, who will attack the player if they are chatted to while scared.

**Comment by copperwater** [comment]
This is because attack() is called in domove_core() here: https://github.com/NetHack/NetHack/blob/ef4efdb1256b8ef68d3009ac144817e46ef75ecd/src/hack.c#L1686

whereas the displacement checks happen 200 lines after that: https://github.com/NetHack/NetHack/blob/ef4efdb1256b8ef68d3009ac144817e46ef75ecd/src/hack.c#L1897-L1905

I think the correct solution is to move the checks for the cases where you end up not moving to just before the attack() call, rather than where they are now, and leaving the cases where displacement actually happens for later. (This would also remove the need for the didnt_move hack where it has to undo the movement in those cases, because now you wouldn't have moved to begin with.)

A minor ramification would be that failing to displace a monster for whatever reason would exit earlier from domove_core(), overriding some other messages - "You are rooted to the floor", "You are trapped in a pit", etc. Though this already happens with "You stop. Foo is in the way!" printing before those other messages, so I don't see a problem with it.
