### ISSUE TITLE
Can't enter Rodney's Tower?

### ISSUE THREAD

**Issue by MLucient** [NetHack/NetHack#476]
Hi all - I'm playing the 3.7.0 branch and seems like I found an odd bug. It looks like the secret door to the moat surrounding the Wizard spawned in an unreachable place? 

![yendor_door](https://user-images.githubusercontent.com/5931657/111939788-8e803000-8aa3-11eb-9ea8-8e0e6be3ff63.PNG)

Luckily not a huge problem for this run since I have an earthquake drum, but I don't recall this happening ever before.

**Comment by entrez** [comment]
What version info is printed when you press 'v' in-game?

**Comment by MLucient** [comment]
Windows NetHack Version 3.7.0-16 Work-in-progress - last build Fri Feb 14 15:41:10 2020 (x86), which is consistent with where I pulled it from: https://github.com/NetHack/NetHack/releases/tag/NetHack-3.7.0_WIP-2020-02-14

**Comment by entrez** [comment]
This bug was fixed after that release (ae471e71b2 on 2020-03-10), but I guess there aren't any more recent prebuilt Windows binaries.  If you compile the game yourself from more recent 3.7.0 sources (once you are done with your current game, since your save file wouldn't be compatible with the current version of 3.7.0) you shouldn't encounter the issue any more.

**Comment by MLucient** [comment]
Oh jeez - looks like I'm having a time-skip-COVID thing; I kept reading that release as Feb of this year, but ...it's 2021. Yeah, I'll compile locally and close the issue; thanks so much, sorry to waste time!
