### ISSUE TITLE
Nethack 3.6.6 ignores the option file

### ISSUE THREAD

**Issue by odisseus** [NetHack/NetHack#500]
I have tried to disable autopickup by adding an option to the nethackrc file, but when I start a new game, the autopickup is still enabled. I've tried configuring other options such as pet name and mouse support, and they have no effect either.

I'm using Nethack 3.6.6 from an [AUR package](https://aur.archlinux.org/packages/nethack-x11/) for Arch Linux. 
```
$ nethack --version
Unix NetHack Version 3.6.6 - last build Sat May  1 04:49:29 2021
(41aaa1a46bc9ee9ec08ab3710aba7ed849a6e187).

```
Here's my configuration file:
```
$ cat ~/.nethackrc
OPTIONS=!autopickup

```

**Comment by ostrosablin** [comment]
This is most likely an issue with AUR package, it's possible that they build NetHack with a wrong config file set and it looks elsewhere, rather than in ~/.nethackrc

As I build NetHack from source, I can confirm that as long as NetHack is built to read config from ~/.nethackrc, it does actually read it from there. So if this doesn't work in AUR package, it's either configured to use some other file, or it's a bug in AUR package.

You can check PKGBUILD to see if package change default location and name of config file, Also, make sure your ~/.nethackrc has proper permissions.

Best bet would be to report the issue to AUR package maintainer.

**Comment by nhmall** [comment]
In 3.6.6, perhaps you could try
nethack --showpaths
to try to verify where the game is looking.
