### ISSUE TITLE
Buffer overflow if savefile path is too long

### ISSUE THREAD

**Issue by amateurhourrrr** [NetHack/NetHack#507]
If the directory of your saves is too long, a strcpy can cause a buffer overflow when starting Nethack

As an example consider filename:
/home/george/Documents/aur/Nethack/nethackdir/var/save/1000wizard (64 chars)

The strcpy occurs here:
https://github.com/NetHack/NetHack/blob/NetHack-3.7/src/files.c#L1356

A corresponding address sanitizer report can be found at
https://0x0.st/-BWX.log

I'm not sure what the appropriate fix is or whether this is something I've misconfigured during compilation

**Comment by pat-rankin** [comment]
The code you've cited thinks it's operating on "save/1000wizard" rather than the file name with full path.  So your configuration is different from what is expected somehow.  (Not necessarily misconfigured; possibly performing external compression on a configuration where that isn't expected.)

The code in question needs to be fixed to avoid overflow, but that's separate from figuring out why you're seeing the file name behavior you're seeing.

**Comment by amateurhourrrr** [comment]
is there any information I could provide to make it easier to figure out? If I breakpoint at that line the variable `filename` contains that full list of characters

it appears to get it via the return value of `fqname` returning that full path

**Comment by pat-rankin** [comment]
You evidently have PREFIXES_IN_USE defined.  That's normally a Windows thing, but it ought to work correctly on other platforms.

Windows doesn't use external compression, so the combination of that with PREFIXES_IN_USE apparently never got adequately tested.
