### ISSUE TITLE
Game closes terminal on exit

### ISSUE THREAD

**Issue by beef623** [NetHack/NetHack#516]
I'm running on OpenSuse and the game is closing my terminal when I exit.

This happens if I run it from Yakuake, Konsole or Xterm. If I run from one of the text consoles, it logs me out on exit.

I'm on the 3.7 branch and didn't change anything in hints. When I run the game, I'm running the ~/nh/install/games/nethack script.

If I edit the last line of that script and replace the 'exec' with '/bin/sh -c' it works normally. Is there a compile option to change the default behavior?

**Comment by amateurhourrrr** [comment]
Hi there, I'm guessing you're the same beef623 that posted on [reddit](https://www.reddit.com/r/nethack/comments/nhu7m9/prevent_terminal_from_closing_on_exit/)?

I think your alias shouldn't source the script, it should just run the script instead,
I think that's where the problem lies

e.g.
`alias nethack="~/nh/install/games/nethack"` rather than including the dot

**Comment by beef623** [comment]
Yes, that was it, thank you.
