### ISSUE TITLE
Qt Gui Support

### ISSUE THREAD

**Issue by CorentinDeBoisset** [NetHack/NetHack#525]
I am on Macos and I managed to build the Qt Window port on the branch `NetHack-3.7`. However, it seems like this window port is using many unsupported features, is there a need for an update of this window port, in order to be fully compatible with the latest Qt releases ?

Would there also be a need to be a portable version of the QtNethack port without having to install all the qt libraries ?

Finally, I can't manage to make the arrow keys work in the application to control the player or the cursor, I believe I played a version like 10y ago and they were working at the time.

**Comment by pat-rankin** [comment]
The Qt interface requires Qt 5, which was the latest at the time when nethack's use of Qt was being brought up to date (it was originally written for Qt 2, and each version of Qt has tended to be incompatible with earlier ones; it got modified to be buildable with Qt 4 but that probably never reached a state that would be described as playable).  Only a relatively small subset of qt5 is required; both homebrew and macports offer the necessary parts without retrieving and installing the whole thing.

It has not been updated to Qt 6, nor is it likely to be any time soon.  qt6 has dropped support for older versions of OSX which are still in active use.  If you're using macOS 11.x and it requires Qt 6, you're out of luck.

> using many unsupported features

Such as?  That sounds like you're trying to use Qt 6 and it has changed features which were fully supported by Qt 5.

> Finally, I can't manage to make the arrow keys work in the application to
> control the player or the cursor, I believe I played a version like 10y ago
> and they were working at the time.

I never used Qt back then, so don't know whether or how the arrow keys worked.  That was during the twelve year span where 3.4.3 was nethack's current version, and the Qt interface was set to expect Qt 3 but not actively maintained.

With 3.6.x and to-be-3.7, the arrow keys are used to pan the map from side to side and/or up and down when it is too big to see all at once.  If it fully fits, pressing any arrow still requests panning but there is no visible effect.  There isn't any option to switch from that to use for movement.

NetHack's number_pad option is supported, so you could switch to digits instead of hjkl&c, but that's mainly useful if your keyboard includes a numeric keypad.  Unlike arrows, both hjklyubn and the keypad can be used for diagonals.

**Comment by pat-rankin** [comment]
I don't know whether the set up instructions in the 3.7 repository are particularly up to date.  You should use
 cd sys/unix && sh setup.sh hints/macOS.2020 && cd ../..
/or/
 sh sys/unix/setup.sh sys/unix/hints/macOS.2020
to create the various Makefiles.  You can get by without editing any of them if you pass arguments to 'make'.  But be sure to use that most recent hints file during setup.

For to-be-3.7, you also need to follow that with
 make fetch-Lua
before attempting to build nethack.  (It's a required step even if you already have Lua on your system.)

Then,
 make WANT_WIN_QT=1 QTDIR=/full/path/somewhere all
where /full/path/somewhere depends upon where the Qt libraries and their header files are installed on your system.  If you use homebrew to acquire and install them then the value for that location in macOS.2020 is already accurate.  I don't, so I specify something on the make command line.

That will build a single instance of nethack supporting both the tty and Qt interfaces.  You could also add WANT_WIN_CURSES=1 for curses, and if you have XQuartz installed you could also add WANT_WIN_X11=1.  Or WANT_WIN_ALL=1 will build all four of them into the program.  (It isn't really "all"; it doesn't include the mswin interface for Windows, for instance.)  Note that WANT_WIN_TTY=0 will *not* avoid including the tty interface.

After 'make WANT... all' then
 make install
will build the data files and copy them and the program to ~/nethackdir/.  There are various arguments you could pass to make in order to produce a system-wide install.  For that you'll need to use 'sudo make install' in addition to whatever other changes are needed.  You don't need--and probably shouldn't use--'sudo make all' for the earlier step.

Note that 'make install' starts by clearing out the target directory, so don't point it at anything you want  to keep.  After you've successfully run it once, you can use 'make update' instead to install revised versions.  'make update' does not clobber stuff that's already there except for the game files it is actively replacing.

If you don't bother editing include/config.h and/or include/unixconf.h (which is the applicable configuration header for OSX and macOS) before 'make all', then the tty interface will be the default one.  To run the Qt one, you can create ~/.nethackrc, or edit it if you already have one, to specify
 OPTIONS=windowtype:Qt
Then you just run nethack normally.  Or you can use
 NETHACKOPTIONS='windowtype:Qt' ~/bin/nethack
or
 NETHACKOPTIONS='windowtype:Qt' ~/nethackdir/nethack
to run nethack.  ~/bin/nethack is a shell wrapper script that runs ~/nethackdir/nethack.  For an ordinary single-user system, you can skip it and run the latter directly.  For a system-wide install, it will normally be in /usr/bin/nethack and the wrapper probably should be used instead of finding (under /Library/something) and running the actual program.

**Comment by copperwater** [comment]
> Finally, I can't manage to make the arrow keys work in the application to control the player or the cursor

This is not a good idea anyway. Don't play like a grid bug, you need those diagonal movements more than you might think.

**Comment by CorentinDeBoisset** [comment]
@pat-rankin Thanks, that's pretty much what I ended up running, after failing with the macosx10.10-qt hint that doesn't work anymore (the cflags/cxxflags are not set using the right variables).

@copperwater  In my memories, typing two arrows at once merged into a single move (up and left at the same time, resulted in an upper-left diagnoal).

--------------------

Also, I tried fiddling with the build system of Qt6, but since they ditched the previous inclusion system that was based on pkg-config, and instead went completely with cmake, it seems quite complex to plug Qt6 with the templated Nethack makefile system.
I could try to use Cmake to build it all, but changing the whole build system seems a bit like a project of its own, and it may break compatibility with systems I can't test on.

-----------------

> using many unsupported features

Whoops, my bad, I remembered the backport of QtTableView into this repo, but it's been removed since I noticed it.

**Comment by copperwater** [comment]
> @copperwater In my memories, typing two arrows at once merged into a single move (up and left at the same time, resulted in an upper-left diagnoal).

I suppose it's possible that the Qt windowport listens briefly for a second arrow key after the first one is pressed and then transforms that into the appropriate diagonal if one is, but I would be surprised to hear it. The core game code certainly does not support this type of movement, because it simply loops character by character over the input (it's unable to detect key releases or whether two keys are pressed at the same time).

**Comment by pat-rankin** [comment]
Whatever Qt code is used for the map evidently does handle arrow keys in that fashion.  But it takes place before nethack gets the keystroke(s).  See NetHackQtMainWindow::keyReleaseEvent (qt_main.cpp).  It has the following comment (which was written for Qt2 or Qt3 and might refer to behavior that was lost in the conversion to Qt4)
`
    // For desktop, arrow keys scroll map, since we don't want players
    // to think that's the way to move. For handhelds, the normal way is to
    // click-to-travel, so we allow the cursor keys for fine movements.
`
and the code in that routine just translates the directions without doing any direct key interpretation.

I haven't figured out how to turn the arrow key behavior on or off.  I once tried to force handheld mode on OSX (to test something else) and couldn't get things working so gave up on that.

**Comment by chasonr** [comment]
I have compiled NetHack 3.7 against Qt 6 on Mac OS. A test game is currently in progress. I have yet to test whether the modified source remains compatible with Qt 5. The changes from Qt 5 to 6 seem less than from Qt 4 to 5, and certainly less than from Qt 3 to 4.

Some issues that I encountered were these:
* The C macro in include/global.h conflicts with some template usage in Qt 6. It is necessary to undef this macro after every include of hack.h. win/Qt/qt\_main.cpp uses this macro, and it must be recreated under another name.
* The MOC, at least in the Homebrew package, turns up as $(QTDIR)/share/qt/libexec/moc ; it is not in $(QTDIR)/bin . This required changes to sys/unix/Makefile.src so that the hints file could specify the complete path of the MOC.
* QTCXXFLAGS and WINLIB needed to be changed in the hints file.
* QSound has disappeared and I have not identified its replacement. It was necessary to specify QT\_NO\_SOUND.
* QApplication::desktop has disappeared. I used QWindow::screen with whatever window was handy to query the size of the desktop.
* Where integer types are compared with QChar, it is necessary to convert explicitly. Likewise, one instance of QPixmap needed explicit conversion to QBitmap.

Overall, 21 of the 23 .cpp files needed some change. qt\_bind.cpp, qt\_key.cpp, qt\_main.cpp, qt\_menu.cpp, qt\_stat.cpp, qt\_win.cpp, qt\_xcmd.cpp and qt\_yndlg.cpp required changes other than `#undef C`. Changes were needed in sys/unix/Makefile.src and sys/unix/hints/macOS.2020 .

Homebrew still offers Qt 5. To compile with Qt 5, it is necessary to change the QTDIR definition to read:
`QTDIR=$(shell brew --prefix)/opt/qt@5`

I'll be back with a pull request after I have completed a test game, checked for continued compatibility with Qt 5 and tested on Windows, and on Linux if any major distribution currently offers Qt 6.

**Comment by pat-rankin** [comment]
> one instance of QPixmap needed explicit conversion to QBitmap.

Was that for the paper doll?  When glyphs underwent a substantial change recently, the paper doll inventory subset got messed up.  Fixing the main problem turned out to be trivial, but there is still a problem when wielding a two-handed weapon.  Its tile is intended to be shown as-is in one hand and in mirror image in the other.  (That's new since your earlier work on this stuff.)  That worked ok for me before the glyph changes, but now I see some blobs that I suspect represent a giant ant in the opposite hand instead of the flipped weapon tile.  I'm not a C++ programmer by any stretch of the imagination and so far haven't seen what the problem is.

**Comment by chasonr** [comment]
The QPixmap that needed conversion was nhsplash.xpm, in the NetHackQtBind constructor in qt_bind.cpp.

The modified sources still compile against Qt 5, at least on Mac OS. I have pushed a branch to my fork with the changes:
https://github.com/chasonr/NetHack/tree/Qt6

**Comment by pat-rankin** [comment]
The #undef C could/should probably go into qt_pre.h instead of being replicated a bunch of times.

**Comment by pat-rankin** [comment]
> The modified sources still compile against Qt 5, at least on Mac OS.

I didn't get very far.

../win/Qt/qt_bind.cpp:98:24: error: no member named 'screen' in 'QFrame'
        splash->move((splash->screen()->size().width()-pm.width())/2,
../win/Qt/qt_bind.cpp:99:18: error: no member named 'screen' in 'QFrame'
                      (splash->screen()->size().height()-pm.height())/2);

I'm not using the final version of Qt5, but am using the last version of Qt5 which supported OSX 10.11.6, and I'm using old 10.11.6 because it's the last version of OSX that's supported on my hardware.

**Comment by pat-rankin** [comment]
Ok, a workaround for the screen() issue is not very pretty but is straightforward.

#if QT_VERSION < 0x060000
#define SCREEN() QApplication::desktop()
#define SCREEN1(dummyarg) SCREEN()
#else
#define SCREEN() screen()
#define SCREEN1(qt6arg) qt6arg->SCREEN()
#endif

and use SCREEN1(splash) in qt_bind.cpp, SCREEN() in qt_main.cpp and qt_menu.cpp.  That was the only issue I encountered  with the older version of Qt5 I'm stuck using.  I can't actually test the Qt6 implementation though.
