### ISSUE TITLE
attributes overview shows setting for autopickup

### ISSUE THREAD

**Issue by erwindon** [NetHack/NetHack#532]
When displaying the attributes overview, either in-game (^X) or on-death, one of the items that is shown is "Autopickup".
However, that is not an attribute, but it is a setting and thus does not belong in that list.

**Comment by pat-rankin** [comment]
If there was room on the status lines, autopickup and pickup_types would be shown there because it would be useful to be able to check them at a glance.  One of the goals for ^X is to show all the status fields fully spelled out instead of with the terse abbreviations that status is forced to use.  And it shows a variety of additional things which are omitted from status due to lack of space.

Whether or not autopickup is enabled, and for what classes of objects when it is, is certainly relevant to end of game disclosure in addition to having those be more easy to check during play.  That probably ought to include auto-open, auto-unlock, and auto-dig too, but the line has to be drawn somewhere.
