### ISSUE TITLE
May be bug in the obj_pmname function

### ISSUE THREAD

**Issue by Meklon2007** [NetHack/NetHack#534]
Hello, when i made many Kobold Zombie in wizard mode and killed them until one of them drops something. And then i try look or step on this, and after that the game was crashed:

![net_hack_error](https://user-images.githubusercontent.com/12417354/122104060-ea96ee00-ce1f-11eb-8f09-02514ec4e019.png)

**Comment by entrez** [comment]
It seems like this applies to any monster where `mkcorpstat` is passed an actual monst  pointer when creating a corpse, so various undead but also tame creatures, reviving monsters like trolls (edit: and the riders), etc (looking at `KEEPTRAITS`).

The direct source of the problem seems to be that `save_mtraits` zeroes out the `data` pointer when saving the `omonst` information.

**Comment by actual-nh** [comment]
@Meklon2007: What version?

**Comment by entrez** [comment]
@actual-nh: This seems to have been introduced in the most recent commit, 57e970b.

**Comment by Meklon2007** [comment]
version - NH 3.7.0-35 (current development)
