### ISSUE TITLE
Missing Izchak's lighting store in "Bustling Town"

### ISSUE THREAD

**Issue by Luxidream** [NetHack/NetHack#555]
![image](https://user-images.githubusercontent.com/35581102/126590709-ccf74c20-48e1-4383-8734-a2cb9b88cd83.png)
![image](https://user-images.githubusercontent.com/35581102/126591026-4e56e243-58a8-480b-9e6a-dc2479b89419.png)

**Comment by bhaak** [comment]
Verified to be an issue since commit 4050ec16700b.

**Comment by entrez** [comment]
I think the problem here is that `shared_with_room` is counting the exterior wall of a room as part of its interior, since it has the right `roomno`.  For example, it thinks that the door highlighted in red opens into the room highlighted in yellow, so adds that door to the yellow room.  Then when it comes time to place the shopkeeper next to the door, it tries to put him next to the red door, and it turns out there are no valid spots that are actually in the interior of the shop.

![Screen Shot 2021-07-22 at 10 06 33 AM](https://user-images.githubusercontent.com/40038830/126654416-13df81fb-2563-49f2-ab20-62f51d0df50c.png)

I think it can be solved by modifying the checks in `shared_with_room` to verify that `x+1 >= droom->lx`, etc, or something similar to verify the door opens to the interior of the room in addition to just checking the `roomno`.

Not 100% certain if I'm understanding it right, but after I made this change I generated a bunch of Minetowns without getting the associated `impossible` ("where is shopdoor?"), and Izchak seemed to be in his shop each time:

```diff
diff --git a/src/sp_lev.c b/src/sp_lev.c
index 33c13e1f8..efd95dae4 100755
--- a/src/sp_lev.c
+++ b/src/sp_lev.c
@@ -980,13 +980,17 @@ shared_with_room(int x, int y, struct mkroom *droom)
         return FALSE;
     if ((int) levl[x][y].roomno == rmno && !levl[x][y].edge)
         return FALSE;
-    if (isok(x-1, y) && (int) levl[x-1][y].roomno == rmno)
+    if (isok(x-1, y) && (int) levl[x-1][y].roomno == rmno
+        && x-1 <= droom->hx)
         return TRUE;
-    if (isok(x+1, y) && (int) levl[x+1][y].roomno == rmno)
+    if (isok(x+1, y) && (int) levl[x+1][y].roomno == rmno
+        && x+1 >= droom->lx)
         return TRUE;
-    if (isok(x, y-1) && (int) levl[x][y-1].roomno == rmno)
+    if (isok(x, y-1) && (int) levl[x][y-1].roomno == rmno
+        && y-1 <= droom->hy)
         return TRUE;
-    if (isok(x, y+1) && (int) levl[x][y+1].roomno == rmno)
+    if (isok(x, y+1) && (int) levl[x][y+1].roomno == rmno
+        && y+1 >= droom->ly)
         return TRUE;
     return FALSE;
 }
```
