### ISSUE TITLE
Attempting travel when interrupted by a monster can restrict all non-movement actions

### ISSUE THREAD

**Issue by Luxidream** [NetHack/NetHack#559]
When travel is interrupted by a monster, repeated attempts to travel may result in a message "You can't get there from here...". When in this state, attempting to perform any non-movement actions will also produce this message with no effect.

![image](https://user-images.githubusercontent.com/35581102/127297505-40852ec5-6d35-40bb-8282-05c8667014e5.png)

**Comment by entrez** [comment]
I'm not seeing this message, but I do get some similarly weird behavior when traveling and stopped by a monster, if I then try to resume travel (via the normal <kbd>\_</kbd> command instead of `#retravel`): the first press of <kbd>\_</kbd> allows me to reselect a destination, but nothing appears to happen right away, even if the path to the destination is clear. If I then press <kbd>\_</kbd> a second time, my character starts moving, but the behavior doesn't seem exactly like normal travel: my character attacked a monster blocking the way at one point.

Edit: I get the same thing where non-movement commands don't work immediately after the initial attempt to resume travel (the one that allows you to select a destination but doesn't actually start moving the character).

The problem that I am seeing looks to have originated in 433f0cc15fba7296d0e12c8fdd22a0ab47d6ace1 based on quick git bisect.

**Comment by entrez** [comment]
A remaining issue I notice after c0c617c4135ddd2f9dbf87fbf1a5d655cab70a1f: once interrupted, it seems to be impossible to resume travel.  After you're interrupted by something 'interesting', when you try to begin traveling again without manually moving away from the 'interesting thing', a turn passes but you don't actually start moving.

This actually seems to be an issue with attempting to travel while adjacent to an "interesting thing" in general, regardless of whether it is a monster that had interrupted your travel mid-run.  In a scenario like this, where my character is orthogonally adjacent to a closed door, travel seems completely impossible regardless of destination:

    -------
    |.....|
    |.....|
    +@....|
    |.....|
    ----.--

Just a guess, but maybe this is related to the thing I mentioned the other day: that the 'set up and begin travel' stuff has been moved from near the start of `rhack` to a bit further down, after the point where parts of the function previously acted on the changes.  Maybe previously the character would take a step before `lookaround` was first called when starting travel, but now `lookaround` precedes that first step, allowing the character to get 'stuck', or something along those lines?

By the way, not really on-topic to this issue but a lot of the code in `moveloop_core` is indented one level too many.

**Comment by entrez** [comment]
I said something about this on IRC but thought it may be good to reiterate here in a more permanent place.  The `NHKF_TRAVEL` case in `rhack` used to set up stuff that then triggered a call to `domove` just a few lines down; now that travel has been moved to the `dotravel_target` function, that `domove` call doesn't get triggered right away.  Adding `domove` to the end of `dotravel_target` seems to fix the behavior I am seeing; it also zeroes out `g.domove_attempting` in the same way as the change in c0c617c, which is probably why that mitigated part of the issue.

```diff
diff --git a/src/cmd.c b/src/cmd.c
index bc872135d..54443d0e0 100644
--- a/src/cmd.c
+++ b/src/cmd.c
@@ -4734,6 +4734,7 @@ dotravel_target(void)
     u.last_str_turn = 0;
     g.context.mv = TRUE;
 
+    domove();
     return 1;
 }
 
diff --git a/src/hack.c b/src/hack.c
index a6a6e2997..0854f041b 100644
--- a/src/hack.c
+++ b/src/hack.c
@@ -3007,7 +3007,6 @@ end_running(boolean and_travel)
     if (flags.time && g.context.run)
         iflags.time_botl = TRUE;
     g.context.run = 0;
-    g.domove_attempting = 0;
     /* 'context.mv' isn't travel but callers who want to end travel
        all clear it too */
     if (and_travel)
```

Applying this patch seems to fix travel for me; my two test cases were:
1. attempting to travel while standing next to a door, as described in the above comment
2. traveling, being interrupted by a monster, and then attempting to resume travel, both via the normal '\_' travel command and via `#retravel`
