### ISSUE TITLE
Font issues on Qt?

### ISSUE THREAD

**Issue by bramtayl** [NetHack/NetHack#566]
I build from source using the linux Qt5 hints. I'm having some issues with fonts maybe? I'm pasting a screenshot below.

![image](https://user-images.githubusercontent.com/9466324/128416726-5efcb4b2-1b5e-45c5-9001-df3a46296d92.png)

**Comment by pat-rankin** [comment]
> I build from source using the linux Qt5 hints.

Are you building 3.6.6 or the pre-release edition of 3.7?  The Qt interface has undergone a lot of changes for 3.7 but they've generally been tested on OSX (using hints/macOS.2020 and 'make WANT_WIN_QT=1') rather than linux.  I don't know what shape the Qt interface was in for 3.6.6.

One of the menus has an entry "Qt settings..." which lets you specify font size but not what font to use.  Unlike regular nethack options, that set of run-time options is managed by Qt and used across games.

**Comment by bramtayl** [comment]
Just did `git clone` so presumably 3.7?
