### ISSUE TITLE
Reflection is bypassed when standing on ice and hit by a ray of fire

### ISSUE THREAD

**Issue by k21971** [NetHack/NetHack#582]
First scenario - player is standing on ice terrain, wearing reflection (amulet, SDSM, doesn't matter which). Monster zaps a wand of fire at the player. The reflection routine does not kick in, instead the ice melts underfoot. The ray of fire will also go beyond the player and affect other things behind them if it has enough range.

Second scenario - player has reflection, standing on lava (w/ fixed water walking boots). Monster zaps a wand of cold at the player. Lava underfoot cools and solidifies, but the reflection routine kicks in and the cold ray is reflected back at the source.

So, some inconsistencies here. Is reflection supposed to be bypassed, as in the ice/wand of fire scenario? Or, if wearing reflection, is the terrain underfoot supposed to be affected if reflection kicks in? Or is all of this intended behavior?

**Comment by eakaye** [comment]
Are you falling into the water and climbing out? If so, then you're not on the same square anymore, so you won't be hit by the ray (unless the new square is next in line), and so reflection and the like don't kick in. This is a little weird timing-wise, but that's probably the way it has to be given that drowning is instant in NetHack. You could I supposed think of it as falling into the water so the ray goes over your head instead of hitting you.

**Comment by k21971** [comment]
If the player is wearing water walking boots while standing on ice and they have reflection, the ice still melts, but since they are still standing in the same spot, reflection then kicks in.

In zap.c line 4554 as part of `zap_over_floor()` for `case ZT_FIRE:` if the terrain is ice (`is_ice(x, y)`) then it immediately melts (`melt_ice(x, y, (char *) 0);`)

If it's possible to climb out, that would be correct, the player is no longer in the path of the ray.

So terrain is affected first before anything happens directly to the player. Perhaps this isn't a bug then. Could use some clarification.
