### ISSUE TITLE
?oSM not scaring @ causes problems in sokoban

### ISSUE THREAD

**Issue by Vivit-R** [NetHack/NetHack#603]
In the last game I played, I got to the end of sokoban and cleared out the zoo only to find that the closet that should have had my reward was empty. I searched all over the level and couldn't find it (I had stoned most of the monsters with a cockatrice corpse, including the one who had been carrying the BoH). Since @'s generating in the treasure zoo are not at all uncommon, this seems like it could potentially be a pretty big issue.

My recommendation: apply the scare monster immunity only to uniques and members of the "dungeon staff" – shopkeepers, guards, priests, all @ that will incur murder penalties if you kill them.

**Comment by vultur-cadens** [comment]
Maybe the Sokoban prize doors could be secret doors. I think that would be more effective at preventing monsters from getting to the prize before the player.  Some edge cases like a shapeshifter in xorn form that then becomes human might still be able to get to the prize, but maybe those are rare enough to be ignored.  It would be annoying to search for the doors for players who have sufficiently-negative luck, but maybe that would be extra incentive to complete Sokoban without taking penalties.

**Comment by Vivit-R** [comment]
That would be a decent solution, but there are other reasons why I think that @ shouldn't have blanket immunity to ?oSM—for one, it suggests a distinction between "person" and "monster" that doesn't exist in NetHack. There are also certain places like the barracks and Fort Ludios that spawn with lots of hostile, non-unique @, and making all @ immune to ?oSM removes a major strategy for dealing with these places; I think this is a bad thing, but it could go either way.

**Comment by copperwater** [comment]
Not necessarily advocating for this over scare monster changes, but might I suggest either of two more targeted fixes?

1. The one I most strongly favor is to **make the monster AI for interest in / picking up items on the floor ignore any item for which `is_soko_prize()` is true.** (Also probably `is_mines_prize()` while we're at it, because a dwarf or gnome running off with the luckstone in the Mimic of the Mines happens occasionally.)
2. **Just lock the three prize doors**, since none of the zoo monsters would be expected to have a key. (This has a bit of a balance implication, because it nullifies the strategy of going through the zoo with stealth killing only what's necessary if you lack an unlocking tool and have to kick the door down.)

Or the problem could be solved the xNetHack way - **make treasure zoos only generate animals**, who generally aren't expected to be able to open doors or take an interest in items.

**Comment by eakaye** [comment]
Option #2 could fail if the zoo generated giants, who can bust down doors (not sure if this is possible). #1 sounds reasonable.
