### ISSUE TITLE
How to get the glyphs' meanings?

### ISSUE THREAD

**Issue by Aceticia** [NetHack/NetHack#634]
Hi, I'm a machine learning scientist and I'm working on coaxing an AI to play net hack. I'm interested in finding a way to translate the glyphs into English. I found that one of the kind folks in the nethack bot community has already done something like this in [this document](https://gist.github.com/HanClinto/310bc189dcb34b9628d5151b168a34b0). However, cmap class glyphs (among some others) don't seem to have a nice translation. 

What would be your suggested way to find meaning of these glyphs that are non-monster or non-inventory? Any suggestions would help, thanks. 

If this issue is not supposed to be here, I'll be happy to move the discussion elsewhere. Thank you again for any help.

**Comment by nhmall** [comment]
Are you looking to translate the NetHack glyph values to a text id, like these 3.7 development version glyph values?
https://gist.github.com/nhmall/5f5c577e11ed88ab41e388229e9c5b33

**Comment by pat-rankin** [comment]
So you're trying to have your AI interpret an ordinary map?  Wouldn't it be much easier to create your own symbol set and use runtime options to have the AI play the game using that?  Any player could do that, but I doubt if very many do.   [Well, any player who can modify the text file 'symbols' or persuade the game administrator to do so.]

The ';' command and the '/' choice in the menu for the '/' command both let a player move the cursor around the map and then pick a spot to have it described.  As of 3.6.x., if the 'autodescribe' option is true then each location you move the cursor over while doing that gives a description of that spot (briefer than choosing the spot though).  That's information any player can get so fair game for AI.  It will just report "wall" rather than "horizontal wall" or "vertical wall" so might not be as detailed as you'd like.  There are separate glyphs (internal codes that an AI shouldn't really have access to) and separate symbols (characters drawn to the screen derived from those glyphs) for the various walls (which include corners and T-intersections in addition to the basic ones) but the program deliberately simplifies the player interface by omitting that when describing what's on the screen.  But if you switch to a symbol set which renders them differently from each other, you'll have access to that information without needing to ask the program what the various characters on the map mean.  [In wizard mode, the #terrain command has a menu choice to encode the terrain type in a way analogous to that, although it is directly displaying the underlying map--which does not use glyphs or symbols internally--and not what the player sees on the screen.  It tends to look like gibberish but there is another #terrain choice to display a key for that instead of displaying the map.  For a custom symbol set, the key would be implicit based on fore-knowledge of the symbol assignments.]

The 3.7 development version has undergone some substantial internal changes in this area.  That shouldn't interfere with a player interpreting the map but depending upon how an AI interfaces with the program is could conceivably affect things.

**Comment by Aceticia** [comment]
@nhmall ,
> Are you looking to translate the NetHack glyph values to a text id, like these 3.7 development version glyph values? https://gist.github.com/nhmall/5f5c577e11ed88ab41e388229e9c5b33

Thank you so much. This is exactly what I needed. I quickly scrolled through, although some of these ids look like abbreviated versions of their original meaning instead of pure natural language, it shouldn't be a problem for us. 

If this file differs a lot between 3.6.6 and 3.7, would you also happen to have this for v3.6.6? Since this is the version that is provided from a benchmark platform. I'm sorry I didn't bring this up in the first message.

**Comment by Aceticia** [comment]
> The ';' command and the '/' choice in the menu for the '/' command both let a player move the cursor around the map and then pick a spot to have it described. As of 3.6.x., if the 'autodescribe' option is true then each location you move the cursor over while doing that gives a description of that spot (briefer than choosing the spot though). That's information any player can get so fair game for AI. 

These are some great suggestions. These glyphs are equivalent to the maps we see from terminal, and we also let the AI use the cursor to get more detailed info. In our research (at least this project), we are more interested in whether they can learn to behave like humans, instead of aiming for optimal performance.

**Comment by Aceticia** [comment]
@nhmall ,

Hi, sorry about reopening this issue. I found there are pretty large differences between 3.6.6 glyphs and 3.7 glyphs. Is it possible to extract the glyph meanings for 3.6.6? If it's hard to do, I understand. Thank you.

**Comment by nhmall** [comment]
The code that allowed that was developed post-3.6.6 and takes advantage of the newer 3.7 defsym.h and other heavily modified header files. It wouldn't be trivial to accomplish under 3.6.6. I may be able to take a quick look later, and will update this issue if I do.

**Comment by entrez** [comment]
I took a crack at something similar for 3.6.6: https://gist.github.com/entrez/780b3e4b19ac999357a61d574c01cdee#file-glyphs-txt

[Here](https://gist.github.com/entrez/780b3e4b19ac999357a61d574c01cdee#file-writeglyphs-diff) is the code I wrote to generate the list, as a patch against c2ebfd9, so anyone who wants can check it for accuracy... I'm not a glyph expert like nhmall is, so I can't tell for sure if I missed something, but hopefully it came out alright. :)

After writing this I noticed an issue with the 'swallowed' glyphs (they skipped 'bottom right' instead of 'middle center'); that should be fixed now.  I did say I wasn't an expert...

**Comment by Aceticia** [comment]
@entrez Thank you so much for the effort you put in. For now the few major milestones look fine. Unfortunately I don't have a way of checking other than my eyeball and corroborating with the previous documents I posted, but I'll let you know if I run into any problems.

Again, I really appreciate your help and @nhmall and @pat-rankin. Converting into natural language is one of THE most important aspect of our project. We will properly acknowledge your help if/once our research bears fruit.

**Comment by heiner** [comment]
> I took a crack at something similar for 3.6.6: https://gist.github.com/entrez/780b3e4b19ac999357a61d574c01cdee#file-glyphs-txt

Thanks @entrez! I took the liberty to produce similar logic using NLE's Python NetHack API, here: https://gist.github.com/c5117ed04851c50744779af81825c899
