### ISSUE TITLE
NHAccess Symset appears broken, possibly Unneeded

### ISSUE THREAD

**Issue by BlindGuyNW** [NetHack/NetHack#638]
Impact: The NHAccess symset is mentioned as an accessibility aid for blind players, but it appears to be broken. Consequently, blind players will be confused because the recommendation seems to not work as advertised.

Many of the default symbols are replaced with "#," or "<," which are ambiguous. It is hard to tell what is represented from the symbols alone.

Furthermore, given the recent addition of extended whatis support, among other features, I suggest that the NHAccess symset is a relic of the MS DOS era and is rather unneeded. I would rather see blind users encouraged to use the default ASCII set, which appears to behave reasonably under most circumstances.

**Comment by entrez** [comment]
Unless the devteam has some knowledge that it isn't, I suspect you are right that it's broken.  I found [this](https://web.archive.org/web/20010417204535/http://www.geocities.com/sbobbitt21/audyssey21/trip.html) writeup of the process of coming up with the symset and assisting with NetHack 3.3.0 accessibility from *Audyssey* magazine, written by NHAccess' creator.  His goal for it was to make sure all the symbols used were standard ASCII, apparently because IBMgraphics were enabled by default and he didn't realize it was possible to disable it.

This sounds pretty similar to how the symset looks currently, which he describes as being broken and not looking as intended -- and it seems like the creator himself stopped using it once he realized it was possible to disable IBMgraphics:

> I had sent in the configuration that Adam Taylor and I had worked out to make certain that everything was represented by text symbols. They invited me to join the beta-testers and look for accessibility problems which might exist in the new version. Of course, I accepted the invitation and down-loaded the first version of Nethack3.30.

> My initial impression was not very favourable. The first time I ran it, I was greeted by a number of less than signs everywhere instead of floor-spaces. It looked like there were hundreds of upward staircases. I reported this, and it was quickly determined that the fault lay in my modified configuration file which had not included some new symbols in the version. Fortunately, the old configuration was not required. I learned that all I had to do to get everything represented by text symbols was to change a few settings in the configuration file.

By the way, I found the article a pretty interesting read even apart from the symset question, it includes some interesting historical anecdotes about NetHack development and accessibility:

> A number of interesting trifles were brought to light by the process of testing this new adventure. Two of these have stuck in my mind as being of particular interest. The first of these concerns the floating eyes. These creatures have been the undoing of many a brave adventurer since their gaze can paralyse those who attack them hand to hand. This gives other creatures time to attack the helpless player with impunity until the effect wares off. In an earlier test version, this was not the case. Due to an error in the code, floating eyes were bereft of their deadly power. Their gaze was their only capability. Without it, they could be sliced and diced with neither caution nor mercy. As a totally blind person, I found it poignant and funny to think of the lack of sight in a floating eye.

**Comment by nhmall** [comment]
Is the recommendation to remove that symset from the source tree altogether and remove references from the documentation?

This thread has been open for a while and I haven’t seen anyone jump in requesting otherwise.
