### ISSUE TITLE
Death livelogging

### ISSUE THREAD

**Issue by k21971** [NetHack/NetHack#688]
As of commit 0ac3b08, player deaths are now livelogged under LL_ACHIEVE. Have noticed that not all death events are logged. Example: if the player were killed by a bat, that is livelogged. But if a player dies via slipping off of their steed, or is killed by a falling object, that is not livelogged.

Also, would like to request a new flag for livelogging deaths, LL_DEATHS or however it should be labelled, to keep it separate from other livelog events. Reason: on the Hardfought servers, our channel bot records death events already via entries in the xlogfile, along with extra information not included in the new death livelogs now in 3.7. With the inclusion of a distinct flag for livelogging deaths, we can filter out those via the channel bot and prevent the recent occurrence of double death messages being displayed by the bot. And this would allow us to preserve the code as-is, without any alteration. Thanks.

**Comment by pat-rankin** [comment]
There is only a single place in the code that issues an end-of-game event and it does so for all ending games except for panic.

The text isn't necessarily identical to what ends up in logfile/xlogfile because the event takes place before some fix-ups that get applied for the latter (such as appending "(with the Amulet)").
