### ISSUE TITLE
Cannot pick up part of a stack of gold when other objects are in the pile

### ISSUE THREAD

**Issue by copperwater** [NetHack/NetHack#697]
Reported in xNetHack then reproduced in a vanilla build. When there is gold and at least 1 other object on the same square, the menu created with the pickup command does not allow specifying a count before selecting $. Thus you can either pick up all of the gold, or none of it.

Cases where this does not happen:
* Picking up other stacks of items on the same square as the gold
* If the gold is the only object on the square
* Traditional menustyle

**Comment by pat-rankin** [comment]
I don't follow your description; the first two bullet items combine to cover every possibility.  I can easily reproduce the problem, but testing contradicts the third bullet.

Anyway, this bug is tty-specific and is being caused by commit efea46a93d79846ccd68edc6203a1abf99a90613 from 16 months ago.

Any pending count gets ignored for group selections so treating '$' as a group accelerator isn't using the count you type before '$'.  I haven't attempted to figure out a fix, just temporarily commented out the code from that commit to verify that it is responsible.

**Comment by entrez** [comment]
> I don't follow your description; the first two bullet items combine to cover every possibility.

I think the first bullet means "partial stacks of other items on the same square as the gold can be picked up as usual", but I stumbled on it a bit too.
