### ISSUE TITLE
AUTOPICKUP_EXCEPTION for X:0 wand causes SIGSEGV exception in MS-DOS build

### ISSUE THREAD

**Issue by disperse** [NetHack/NetHack#706]
Steps to reproduce:
- Add `AUTOPICKUP_EXCEPTION=">.*:0).*"` to the NETHACK.CNF
- Launch NETHACK.EXE

Expected behavior: NetHack will run and identified empty wands will not be picked up.

Actual behavior: NetHack crashes with a SIGSEGV error:

```
Exiting due to signal SIGSEGV
Page fault at eip=00263a9e, error=0004
eax=0000006d ebx=00000000 ecx=00313271 edx=0055bc00 esi=0055bc00 edi=00263fd2
ebp=0055bb78 esp=0055bb40 program=C:\NETHACK.EXE
cs: sel=00a7  base=00400000  limit=0057ffff
ds: sel=00af  base=00400000  limit=0057ffff
es: sel=00af  base=00400000  limit=0057ffff
fs: sel=008f  base=00008230  limit=0000ffff
gs: sel=00bf  base=00000000  limit=0010ffff
ss: sel=00af  base=00400000  limit=0057ffff
App stack: [0055cf80..0035cf84]  Exceptn stack: [0035ced0..0035af90]

Call frame traceback EIPs:
  0x00263a9e
  0x00264162
  0x00263660
  0x00184e64
  0x001850ed
  0x000b9d03
  0x001850c0
  0x00185a5e
  0x0016c1d2
  0x000b7c3b
  0x000bb5c6
  0x000bb6e2
  0x000bb7a4
  0x0016d2cb
  0x0016d577
  0x00253a73
  0x00254428
```

**Comment by pat-rankin** [comment]
NetHack shouldn't be crashing for something like that, and presumably someone will figure out how to fix it.

In the mean time, you're specifying a regular expression and parentheses are special within regular expressions.  Switching from bare ")" to "\)" might work as you want and using "[)]" almost certainly will.  That said, nethack doesn't come with its own regex package so is at the mercy of whatever the system it's built on has available.  In my test on OSX, your pattern worked as-is.  The suggested \ and [] variations both did too.

FYI, you don't need the ".*" sub-patterns before and after the part that's of interest.  The old 'globbing' style of pattern matching would have needed "*:0)*" because that operated on full lines.  Changing "*" to ".*" is the no-brainer conversion but regex matching doesn't require that; ":0[)]" would work.  (If you really want a full line match for something, start the pattern with "^" and end it with "$".  Regexp "^.*:0[)].*$" is an exact conversion for glob "*:0)*".   A full line containing zero or more arbitrary characters followed by colon, zero, close-paren followed by zero or more arbitrary characters.)

**Comment by pat-rankin** [comment]
github mangled my previous comment.

It ate the <backslash> in ''switching from bare ")" to "<backslash>)" might work.''

It also used "<period><asterisk>" to switch to italics, removing the <asterisk> in the process (multiple times).

**Comment by entrez** [comment]
@pat-rankin, if you escape those characters with a \\ they'll show up, or you can put them in a code block where they're printed literally by surrounding them with \` characters (so \`foo\` shows up as `foo`).

**Comment by nhmall** [comment]
Since there’s no official binary of 3.6 or 3.7 for ms-dos , perhaps you are building it yourself. If you are building it yourself and therefore have the djgpp compiler available, the symify tool is needed to turn that trace into useful information. 

See
http://www.delorie.com/djgpp/v2faq/faq9_3.html

excerpt:
“Q: My program dies with a cryptic message like "SIGSEGV" or "Page Fault" or "General Protection Fault" and prints some funny-looking numbers. Can't I get some decent human-readable traceback information, so I could pinpoint where in the program did the problem happen? 

A: Those "funny-looking numbers" are the traceback. They describe the sequence of function calls which led to the fatal error by giving you the addresses where each function was called. You can have these addresses translated to source line numbers by using the SYMIFY program. SYMIFY is included in the [basic DJGPP development environment distribution](ftp://ftp.simtel.net/pub/simtelnet/gnu/djgpp/v2/djdev203.zip), and should be in your bin/ subdirectory. To symify the traceback, make sure that your program was compiled with the -g switch, linked without the -s switch and not stripped of its debugging symbols by running the strip utility. Now invoke your program and do whatever it takes to make it crash. Then, with the traceback still on the screen, type this from the DOS command line:

 symify program-name
(Note: program-name should include the .exe suffix.) SYMIFY then walks through the crash traceback by reading it from video memory, and matches the hex addresses to the source files and line numbers of the program. It then writes back the list of source files and line numbers right next to their hex addresses. Now you can start debugging. More info about this is available in [how to analyze crash dumps](http://www.delorie.com/djgpp/v2faq/faq12_2.html).”

**Comment by pat-rankin** [comment]
Unbelievable; even worse mangling.  The second time it took out open-angle-bracket b a c k s l a s h close-angle-bracket.  I can understand the literal reverse slash handling, although treating plain text as markup by default instead of upon request is a terrible misfeature, but changing the spelled out word is outrageous.

For the third try: change plain ")" to "\\)" or to "[)]" and
it is ok to take out ".\*" at beginning or end or both (but you don't have to do so).

[github doesn't support the out of date browser I use and one of the things that doesn't work is switching from 'write' to 'preview' when composing a comment, assuming that that actually does something worthwhile, and another is showing tool-tips for the various editing symbols.]

**Comment by nhmall** [comment]
With the NETHACK.CNF line as written by @disperse in the original posting, and using the NetHack sources from NetHack-3.7 development work-in-progress, you get this:
```
AUTOPICKUP_EXCEPTION=">.*:0).*"
 * Line 6: regex error in AUTOPICKUP_EXCEPTION: parentheses not balanced.
```

With it modified to `AUTOPICKUP_EXCEPTION=">.*:0\).*"`
you get this (it works as expected):

![2022-03-23](https://user-images.githubusercontent.com/9643004/159745724-e998a873-3fbb-45fc-9abf-d7a915c6477c.png)

@disperse didn't indicate what version he was using or where the program was obtained from, but with the current NetHack 3.7 WIP sources cross-compiled for MSDOS, there does not seem to be any issue.

Side-note: the vertical column of giant ants along the right side appears to be an unrelated bug that needs to be fixed.

**Comment by disperse** [comment]
Sorry for dropping the issue and disappearing. I cross-compiled from source the Nethack-3.7 branch about a week ago and ran in DosBox-X. I did notice the giant ants on the right as well. 

I tried escaping the parenthesis with a backslash and it worked without crashing. It seems like it's working as designed and the regex was just incorrect.

**Comment by pat-rankin** [comment]
> Side-note: the vertical column of giant ants along the right side appears to be an
> unrelated bug that needs to be fixed.

vga_clearmap() is setting tileidx to 0 which doesn't match the glyph value used
(which should be changed from S_stone to S_unexplored for columns 1..COLNO-1
and to either S_unexplored or S_nothing for column 0).

vesa_clearmap() isn't setting tileidx at all and also ought to switch away from
S_stone as the default glyph.

The fact that the ant tiles are appearing on the right rather than the left may
be a separate bug.  If the map is being shifted over to hide unused column 0
and has been sized as if the screen holds 80 columns then it doesn't have
enough data to cover screen column 80.
