### ISSUE TITLE
"The Lord Surtur's corpse glows iridescently."

### ISSUE THREAD

**Issue by copperwater** [NetHack/NetHack#722]
That's the whole bug.

It comes from using shk_your to construct the string, which doesn't have any way to avoid placing an article or possessive on the string.

https://github.com/NetHack/NetHack/blob/eb9c7d77d4f7efe180fc0fa0a62d2db3d944498c/src/zap.c#L915-L928

**Comment by entrez** [comment]
Not directly related, but I noticed that `the()` apparently has issues with Lord Surtur's corpse as well (from `The(aobjnam())` [here](https://github.com/NetHack/NetHack/blob/9da36fb03ea41ca6614013090c2d7922d735217c/src/zap.c#L5678-L5689)):

> Oops!  The Lord Surtur's corpse drops to the floor!

The cause is this rule which prepends "the" as long as an initially capitalized string ends with a space or dash followed by an uncapitalized word, as "Lord Surtur's corpse" does.

https://github.com/NetHack/NetHack/blob/9da36fb03ea41ca6614013090c2d7922d735217c/src/objnam.c#L1911-L1914

I don't know if there are any cases which can actually be encountered in a normal game where `the(aobjnam())` type constructions are used on a unique monster's corpse, though -- I don't think the wishing one can happen outside of debug mode?
