### ISSUE TITLE
Using old records file, no records were written, "scores" does not work

### ISSUE THREAD

**Issue by ville-v** [NetHack/NetHack#736]
Compiled the game with default settings, except global install, on Linux.

Scores: 8t 1a o

1. Tested with records file from old version:
2. At the end of the game with a few hundred points, 100 scores were shown, I don't remember if the old score was shown
3. Checked records file: No new entries from 3.7.0
4. Deleted records file:
5. At the end of the game with 172 points, own score was shown, written correctly to the records file
6. Replaced records in text editor (to ensure permissions of the file were correct):
7. At the end of the game, 100 scores were shown, own score was shown, no new entries in the records file

Because the records file has over 100 entries, starting from 2 points, I expected that the new score would be added and would be shown in between the old records, as indicated by the "scores" setting. I want to save unlimited entries to the records file.

Is this a new compile time setting or a bug?

Records file (renamed to txt): 
[record.txt](https://github.com/NetHack/NetHack/files/8502035/record.txt)

**Comment by entrez** [comment]
I downloaded your record file and experimented a bit.  I think the problem is that `ENTRYMAX` in the sysconf file and/or config.h (depending on compilation settings, I think the sysconf file may not be used) is set to 100 by default, and your record file contains like 150 entries, so you have to get into the top 100 in order to show up.  If you change `ENTRYMAX` to 300 or something you should start having scores show up.  Or even as-is, if you get a high enough score to get into the top 100, 300 points or so, it should show up.

If you really want to save unlimited entries in the record file, and increasing `ENTRYMAX` to a very high number isn't enough, maybe you could modify topten(topten.c) so it doesn't compare the number of entries to `sysopt.entrymax`, something like this:
```diff
diff --git a/src/topten.c b/src/topten.c
index 63d7ea2bd..b9ac30e70 100644
--- a/src/topten.c
+++ b/src/topten.c
@@ -791,15 +791,9 @@ topten(int how, time_t when)
                 continue;
             }
         }
-        if (rank <= sysopt.entrymax) {
-            t1->tt_next = newttentry();
-            t1 = t1->tt_next;
-            rank++;
-        }
-        if (rank > sysopt.entrymax) {
-            t1->points = 0;
-            break;
-        }
+        t1->tt_next = newttentry();
+        t1 = t1->tt_next;
+        rank++;
     }
     if (flg) { /* rewrite record file */
 #ifdef UPDATE_RECORD_IN_PLACE
@@ -821,8 +815,8 @@ topten(int how, time_t when)
                     char pbuf[BUFSZ];
 
                     Sprintf(pbuf,
-                            "You reached the %d%s place on the top %d list.",
-                            rank0, ordin(rank0), sysopt.entrymax);
+                         "You reached the %d%s place on the top scores list.",
+                            rank0, ordin(rank0));
                     topten_print(pbuf);
                 }
                 topten_print("");
```
I don't know if a change like that could have any other negative consequences, other than potentially creating an enormous record file after a while.  I'd probably just set `ENTRYMAX` to a larger number.

**Comment by ville-v** [comment]
Ok, I found the ENTRYMAX. It seems I have increased it before and forgot it wasn't at the default value.
