### ISSUE TITLE
Projectile unidentification preventing merging is annoying

### ISSUE THREAD

**Issue by vultur-cadens** [NetHack/NetHack#795]
Since ad7f2afef9907ef6e52a17dd446b44d1dc774dbe, the blessed/enchantment/rustproof/container knowledge status of objects becomes unknown when an unseen monster picks them up.

If you throw projectiles at monsters in the dark, it is likely that they will get picked up, and you won't see them get picked up.  This will cause your thrown projectiles to get un-identified, and thus not merge with your main stack of projectiles (if your main stack is identified).  This has negative effects on multishot if you don't have a very large stack, and is annoying if you want to do something like enchant/bless/poison all of your ammunition.

There are ways to defend against this projectile-unmerging (I have tried all of these in my recent games that involved significant usage of ranged weapons):

* Try to only attack monsters that are within range of your light source, reducing the chance that your projectiles land in a dark place and get picked up.  Practically, this means only attacking at close range most of the time, and this somewhat defeats the purpose and fun of using ranged weapons.
* Realize that having formally identified projectiles is actually a bad thing if you want to have fun shooting monsters from far away. If your main stack of projectiles is formally identified, deliberately unidentify it by dropping it, blinding yourself, letting some weapon-using monster pick it up, killing the monster, then retrieving your stack of projectiles.  Drop or bag your projectiles before reading any scrolls of identify, to prevent them from accidentally being identified.  Name them with their enchantment to keep track of them.
  * Beatitude identification can be an exception because items often get cursed in late game, and altars are usually common enough that re-identifying projectiles that have lost known beatitude is easy.  Enchantment and erodeproofness generally require using resources to formally re-identify and you don't really benefit from formally knowing those (once you're done enchanting things), so avoid identifying those.
* Do not erodeproof projectiles.  With high Luck and blessed projectiles, non-erodeproofed projectiles are unlikely to be affected by passive erosion, and thus you will remain ignorant of their erodeproof status.  Conversely, erodeproofed projectiles are likely to be identified by passive erosion attacks regardless of Luck, and thus prevent merging with separate stacks of unknown erodeproofness ([relevant code](https://github.com/NetHack/NetHack/blob/faf3d6f08a73207bc205794cb1e833f960bac5e5/src/trap.c#L243-L260)).  This makes erodeproofed projectiles actually significantly worse than non-erodeproofed ones.

Note that name and thrown status (for pickup_thrown) are preserved even after being picked up by an unseen monster, so your character "knows", in a sense, that they were once part of the same stack, even if they don't merge anymore.

Suggestion: stacks of the exact same blessed/enchantment/erodeproof status should merge with each other regardless of identification status (and their identification statuses should be "bitwise ORed", if different).  Your character can evidently tell that they are the same, because deliberately-unknown identical stacks still merge; why should knowing something about one stack prevent that?

**Comment by ostrosablin** [comment]
This is pretty annoying, indeed. I often carry a filled inventory (unless I find a sack or a bag of holding), so projectiles going unidentified means that I can't even pick them up, unless I drop something. I believe xNetHack has already implemented relaxed stack merging rules, so it would be great if this was ported to vanilla.

It's also pretty annoying if your gems get accidentally BUC-identified, because BUC has no effect on gems, but this will make stacks non-mergeable with same type of BUC-unknown gems. I suppose relaxed stack merging rules is the right thing, because current merging rules just increase the tedium and frustration, since even if you know (informally) BUC of an item, there's no way to make it merge besides intentionally unidentifying items or formally BUC-identifying them on altar.

**Comment by copperwater** [comment]
This has been in xNetHack for quite a while and I've had no complaints so far. I agree completely with the suggestion; there is no clear reason why two items should stack together when you don't know what either of them is (+0 daggers and such), but not be able to stack together when you do know what one of them is.

The commit is https://github.com/copperwater/xnethack/commit/28fc1f4 for any interested devteam members looking to merge it or PR authors looking to make it into a pull request.

**Comment by ostrosablin** [comment]
I've always assumed that (non-priests) can "feel" difference in beatitudes (just can't tell what beatitude is it, exactly), hence unidentified items with same BUC getting stacked.

Another way to think about it is that items with different just resist being stacked (think like anti-magnets, stuff with same BUC is attracted and with different is repelled). This better explains why you can't forcefully stack items with different BUC.

No matter how you look at it, lack of stacking for items with different identification levels looks very awkward. Because if both items were completely unidentified - they would perfectly stack together, physics of game world allows that. Which means that you should (theoretically) be able to at least manually merge such stacks together with #adjust. Since I can't think of a reason, why those stacks can't be physically stacked together (unless laws of physics in NetHack have some crazy quirks preventing to do so).

And since just trying to stack together everything you pick up with #adjust just adds tedium rather than being an interesting game mechanic - I think xNetHack dealt with this the best way possible. As it keeps the logic sound and non-contradicting, while adding no tedium to game (in fact, it reduces tedium compared to vanilla NetHack).

**Comment by vultur-cadens** [comment]
Looks like this was addressed in 86c29f5b47f254a89a9242686665499fdd7722f9
