### ISSUE TITLE
The character recognises water in all circumstances except for as a potion

### ISSUE THREAD

**Issue by amateurhourrrr** [NetHack/NetHack#818]
Clear potions are always water, which one could imagine would be obvious to the character as well.

They recognise fountains, moats, and have presumably been drinking water their entire pre-dungeon lives.

I think it would make sense for clear potions to be identified from the start of the game,
or at least autoidentified when dipped into

**Comment by pat-rankin** [comment]
Holy water and unholy water are not separate types of item.  If water isn't discovered yet, just name either of them "water" and all three BUC types are set.

You can discover potion of water by drinking an uncursed one.  Seems like waste of a potion to me.

Dipping many things into uncursed water gives "interesting".  Auto-discovery for that does not make sense at all. Same for dipping something that's already blessed into holy water or already cursed into unholy water.

Auto-discovery when something rusts or becomes blank is probably reasonable.  It's iffy when something glows unless you're a cleric and clerics already start with water pre-discovered due to initial inventory.

**Comment by amateurhourrrr** [comment]
Hi Pat,

I mean if you typename it as 'water' then you get 'blessed potion of water' which sorts differently to 'holy water', doesn't it?
with `sortloot:full` I mean, at least it does in older 3.4.3-based variants which I was recently playing inspiring this issue

Do you see any problems with all roles knowing water from the start of the game?

**Comment by pat-rankin** [comment]
>  I mean if you typename it as 'water' then you get 'blessed potion of water'
> which sorts differently to 'holy water', doesn't it?

The original sortloot behaved that way.  The present sortloot (since 3.6.1)
sorts holy water and unholy water to be adjacent to water.

| commit 4750c0a30378169f9d8d37d302bde659da0cca4b
| Author: PatR <rankin@nethack.org>
| Date:   Sat Apr 23 15:44:26 2016 -0700
|
|     sortloot ordering for holy/unholy water
|
|    When items were sorted alphabetically, holy water ended up in the H's
|    and unholy water in the U's.  Force them to get placed with water in
|    the W's, as would happen if water wasn't given an alternate name when
|    blessed or cursed.

> Do you see any problems with all roles knowing water from the start
> of the game?

Not a problem, but some players like to see their discoveries list gradually
grow as the game progresses.  Making easy to discover items start out as
pre-discovered does them a disservice.  Admittedly a pretty minor one.

**Comment by amateurhourrrr** [comment]
Fair enough then - I still feel like it'd make more sense for the characters to recognise water generally
(they recognise fountains/moats/have presumably drank water their entire pre-dungeon lives)

I'll edit the top post to remove the mention of sortloot

**Comment by copperwater** [comment]
> Not a problem, but some players like to see their discoveries list gradually
grow as the game progresses. Making easy to discover items start out as
pre-discovered does them a disservice. Admittedly a pretty minor one.

My impression is that such players are outnumbered by players who get sick of "Call a clear potion:" prompts every game. To the point where you just want to quaff the dang thing so that the game will tell you it tastes like water and identify it.

**Comment by nhmall** [comment]
> Fair enough then - I still feel like it'd make more sense for the characters to recognise water generally (they recognise fountains/moats/have presumably drank water their entire pre-dungeon lives)
> 
> I'll edit the top post to remove the mention of sortloot

**Comment by nhmall** [comment]
accidental close, sorry

**Comment by NullCGT** [comment]
I actually really like that the player character does not recognize clear potions. From an in-universe perspective, I would argue that it makes some amount of sense. If I was exploring a dungeon and picked up a bottle filled with clear liquid, I think I would make the assumption that it was probably water, but given all the strange and magical bottles of liquid I had previously encountered, I probably wouldn't be sure. It might be poison that just happens to look like water, or it might be saltwater, or it might be angel tears. Who knows?

From an out-of-universe perspective, I think that learning to recognize clear potions is a lot of fun for a new player. It's a bit of meta knowledge that's very easy to learn without looking at the wiki, and can be discovered after only a few games. When one is repeatedly dying to starvation and coyotes in the first few dungeon levels, that little bit of discovery can mean a lot.

As someone who's also played for a long time, I definitely find naming water every game to be annoying, but I think the benefits to the game are worth that minor bit of annoyance.

**Comment by loggersviii** [comment]
>If I was exploring a dungeon and picked up a bottle filled with clear liquid, I think I would make the assumption that it was probably water, but given all the strange and magical bottles of liquid I had previously encountered, I probably wouldn't be sure.

not to mention all the mundane and non-magical liquids someone could have left lying around. Maybe a previous adventurer really liked their vodka!

**Comment by amateurhourrrr** [comment]
I don't believe that I can disagree any more than I do with that opinion, but considering it's such a minor change and there's a lot more nays than yays I'll just close this so more important things can be talked about instead
