### ISSUE TITLE
Strange shopkeeper behavior with magic harp

### ISSUE THREAD

**Issue by youkan700** [NetHack/NetHack#819]
1. Shot a shopkeeper with throwing weapon from outside his shop
2. Use a magic harp to make the angry shopkeeper peaceful
3. The shopkeeper falls into strange condition, which repeatedly asking "Didn't you forget to pay?", even you don't have any debt

This seems to be caused because charm_monsters() in music.c does not check if a given monster is a shk, while maybe_tame() in read.c checks it and calls make_happy_shk().

**Comment by entrez** [comment]
What is the normal circumstance under which this behavior is meant to happen?  Following the hero throughout the level and chiding her to pay up while peaceful, then eventually getting angry at repeated refusal to pay?  It's pretty cool but I've never seen it before.

I thought maybe it could be encountering your own bones where you previously angered the shopkeeper, since the "Hello, player!  I was looking for otherplayer." message in [that block of code](https://github.com/NetHack/NetHack/blob/67ec92165eeb01c54d2f8599736f956672b806f3/src/shk.c#L3947-L3969) appears under similar circumstances.  But in that case the shopkeeper appears to be either fully satisfied by getting her money from your corpse, or else is still angry and continues to attack you.  Is something like this actually the way it's meant to be encountered, or is there some other way to trigger it?  Or has the original way to trigger it become impossible over the years?

**Comment by youkan700** [comment]
Please try to recreate the symptom by exactly following the steps. You don't need any bones nor specific previous state.
The expected behavior is "Satisfied, <the shk> suddenly disappears!" or "<The shk> calms down." as same as the case of using a scroll of taming or a charm monster spell. Using magic harp causes problem.

**Comment by entrez** [comment]
I think you are misunderstanding my comment -- I have reproduced it using the steps you indicated, but it's clearly deliberately programmed in for some reason.  Since I have never encountered it before, I'm curious whether this is the reason (the choice of limiting it to a magic harp would be somewhat odd, but failing to provide an alternative message for a hero without any debts might just be an oversight) or whether there is some other way this shopkeeper behavior might happen in a normal game.  There's no problem with how you described it, the instructions are clear -- I'm just curious about how it's meant to work.

**Comment by entrez** [comment]
@bhaak pointed out this shopkeeper behavior is inherited from Hack -- glancing over the code it looks like theft used to trigger this behavior instead of immediate anger/kops.  Seems doubtful that there's still a legitimate way to trigger it in modern NetHack (other than this apparent bug).

And it looks like in Hack 1.0.2, sometimes the shopkeeper wouldn't even make the effort to follow you, and would let you get away clean (with a chance depending on the store type).  Pretty interesting.
