### ISSUE TITLE
Implications of Monster Knockback

### ISSUE THREAD

**Issue by NullCGT** [NetHack/NetHack#824]
I wanted to talk about https://github.com/NetHack/NetHack/commit/0bca93be87d6a92bef9f2fd113276bc827623a9e. First, a bit of provenance: I wrote the original monster knockback feature in SpliceHack, and it was later ported to EvilHack by K2. 

Second, monster knockback as implemented here changes the game in some ways that I think may not be intended, When I first implemented monster knockback in SpliceHack, players discovered that crashing into a wall via hurtling can result in the player being left vulnerable for several turns, since hurtle_step() does not reset `nomul()` when colliding with a wall. This means that a monster could knock a player into the wall, causing them to lose turns, then knock them into the wall while they are unable to move, causing them to lose turns again, and so on and so forth. Players that encountered this were, naturally, extremely displeased. The comments in `hurtle_step()` suggest resetting `nomul()` when stopping; now that monster knockback has been added to the game, updating `hurtle_step()` is an absolute necessity.

Additionally, I noticed that this implementation of monster knockback has a chance of stunning the player. While I like this in theory, I'm worried about the difficulty implications of such a change. Consider a common lategame situation, in which the player is fighting Orcus. Each of Orcus's claw attacks has a one in six chance of causing the player to hurtle, and a further one in four chance of stunning the player. This means that in a single round, Orcus has a not insignificant chance of stunning the player, making them unable to cast spells, in addition to his usual poisonous sting, dangerous spellcasting, and damaging physical attacks. All of this is assuming that `hurtle_step()` is changed so that it resets `nomul()`, and Orcus does not get to attack the player multiple turns in a row. I think this example illustrates how much more dangerous this change makes huge size endgame monsters, particularly spellcasters like Demogorgon and Orcus.

I'm strongly in favor of changes that make the combat in NetHack more interesting, and given my personal investment in it I think knockback is a great addition, but I worry that this change may have much farther reaching consequences than anyone realizes.

EDIT:

K2 pointed out that the knockback range in vanilla and EvilHack is only 1-2 squares, which makes the change to hurtle_step() much less pressing than I may have indicated at first. A 2-tile hurdle could still be potentially dangerous.

**Comment by copperwater** [comment]
Speaking of 2-tile hurtling, I have also noticed some confusing behavior (don't really think a bug is in play here). When I first read the knockback commit, I thought "oh no, a monster could knock you back 2 tiles to a spot in the water with no land nearby and instadrown you". Krakens are the only sea monster that can do this, but any knockback monster on land could also do it. However, in practice, I never hurtle 2 spaces over the water - even after hardcoding the knockback to always hurtle 2 spaces. I always fall in on the first move over water, which seems counterintuitive - this isn't how it works if e.g. hurtling after a thrown iron ball, for instance, which carries you over multiple water spaces. I don't *want* the player to be able to cheaply instadrown, but what is the distinction between these?

As for certain bosses stunning the player, I don't necessarily think it's a bad thing that they may sometimes drive even a powerful spellcaster to have to use an item to flee. It's a less interesting game if they're deliberately kept below that threat level. Stun*locking* the player so that they never really get the chance to take actions, on the other hand, should definitely be avoided. Even if it's a low-probability chance. It's similarly a less interesting game if escape items become *mandatory* to guard against a cheap death when fighting Orcus.

The best way to ensure the change to hurtle_step happens as you want is probably to make a pull request for it.

**Comment by entrez** [comment]
> I never hurtle 2 spaces over the water - even after hardcoding the knockback to always hurtle 2 spaces. I always fall in on the first move over water, which seems counterintuitive - this isn't how it works if e.g. hurtling after a thrown iron ball, for instance, which carries you over multiple water spaces.

I have noticed this before too and assumed it was a deliberate choice to avoid forced drowning from something that wasn't a deliberate "move me into the water" action like throwing an iron ball would be.

**Comment by pat-rankin** [comment]
Re alternate behavior when hurtling over water:  I haven't looked at the code involved but am fairly sure that it is an intentional difference between recoil while floating/flying above the floor/water versus sliding backwards across the floor until encountering water which can't support the hurtler.

**Comment by pat-rankin** [comment]
While fixing #836, engulfed while mounted, I ran into a situation that breaks movemon().  That has been avoided, but knockback of one monster by another into a hole, trap door, or magic portal can cause the same breakage.  movemon() caches the next monster that will move, and it if gets transferred to the migrating_mons list it will still move next.  When it does, set_apparxy() will mess up its intended destination, and if its nmon pointer points to another migrating monster rather than be Null for the end of the list, movemon() will try to move that one next.  Lather, rinse, repeat.

Old versions of nethack used to rescan fmon looking for a monster who hadn't moved yet after every monster that moved, primarily because the next one in the list might have been killed and removed from fmons so couldn't be cached.  That was a lot of overhead on heavily populated levels, particularly for underpowered hardware.  Someone contributed a change that kept dead monsters on the list until the end of the turn so that it doesn't need to be rescanned from scratch over and over and over.  But that code includes a comment that the only monster who can be moved from fmon to migrating_mons is the one that's currently moving.  (In practice that could be "or who has already moved this turn".)

So the new knockback code has a much more serious issue that stunning the hero.  I've no idea whether the code it was based on suffers from the same problem.

**Comment by paxed** [comment]
This should be fixed by d91915dba3972

**Comment by NullCGT** [comment]
As noted by paxed, this is fixed, so I can close it out.
