### ISSUE TITLE
Valkyrie and Excalibur

### ISSUE THREAD

**Issue by NullCGT** [NetHack/NetHack#825]
In light of the recent change to Valkyrie's starting inventory, I wanted to suggest changing their starting inventory to match the Slash'Em implementation: 

- Human Valkyrie start with a longsword, as they did in 3.6 and earlier.
- Dwarven Valkyrie start with a spear, as all Valkyrie currently do in 3.7.

In 3.6 and earlier, Valkyrie were an excellent way of introducing new players to the game. While making it harder for Valkyrie to obtain Excalibur makes sense from a flavor and lore perspective, easy access to Excalibur was part of what made Valkyrie a fun to play, particularly for newer players.

I think that giving a different starting weapon to human and dwarven valkyrie would split the difference: The role would still provide an easy route for beginners to penetrate deep into the dungeon, while also aligning more closely with NetHack's lore. Additionally, the difference in starting weapon would help distinguish between two races, which is something that NetHack has historically struggled with.

**Comment by copperwater** [comment]
Strongly disagree. I don't see "[Human] valkyries need to keep their status as the most newbie-friendly role, because that's the way it's been historically" as particularly compelling. There are other new-player-friendly roles such as Barbarian, so it's not like the game is becoming too difficult to break into.

Meanwhile, I do find the reasons behind the change compelling. Knights already have an easy path to Excalibur, so removing this from Valkyries helps greatly with role differentiation and avoiding them playing the same way, at least in the early game. In fact, I'd like to see it taken further, with something that circumvents basic Valkyrie strategy advice now being "just wait until you find a long sword and then dip it for Excalibur". While race differentiation is a good goal, I think it should be a lower priority than the role differentiation that was achieved with the spear change. (And note, the spear change didn't actually hurt race differentiation - it actually added a bit of it since now dwarven valks have a different spear than humans, whereas there is no dwarven longsword.)

**Comment by k21971** [comment]
> In fact, I'd like to see it taken further, with something that circumvents basic Valkyrie strategy advice now being "just wait until you find a long sword and then dip it for Excalibur".

A couple variants do this already, making it so only a lawful knight can dip for Excalibur.

**Comment by eakaye** [comment]
I like the idea of giving dwarves a spear instead of a longsword as a way of balancing the races, like the way elven Rangers get an elven cloak instead of a cloak of displacement. Since Valks are terrible spellcasters in any case, there's no real disadvantage to being a dwarf, unless you're _really_ so desperate for a slightly more merciful Mysterious Force that you want to be neutral. Having a dwarven Valk start with a worse weapon would make lawful human an option worth considering.
