### ISSUE TITLE
Access to freed memory with --nethackrc

### ISSUE THREAD

**Issue by schauveau** [NetHack/NetHack#832]
I noticed a problem with the `--nethackrc` option in the Nethack-3.7 banch.  
The command line is processed in `unixmain.c` and the filename is stored as a `char*` in `g.cmdline_rcfile` 

In file options.c, that pointer is copied to a local variable, freed and then the local variable is used which is obviously incorrect.

```c
        const char *envname, *namesrc, *nameval;
        ...
        nameval = g.cmdline_rcfile;
        free((genericptr_t) g.cmdline_rcfile), g.cmdline_rcfile = 0;
        ...
        /* and do stuff with nameval  ... */
```
https://github.com/NetHack/NetHack/blob/fd3b4384c3684b63964c213b8e82b2ff35212b30/src/options.c#L6235

**Comment by entrez** [comment]
Good one.  When I run `./nethack --nethackrc ~/.nethackrc` it gives me an error message like `Access to @Un5 denied (2)`, presumably as a consequence -- surprised nobody has run into that before.

I also got `Access to !L0L denied (2).` which makes me feel like NetHack is mocking me a bit. :)

**Comment by schauveau** [comment]
Probably because `--nethackrc ` is not well documented. People are probably using  `NETHACKOPTIONS=@filename` instead.

**Comment by pat-rankin** [comment]
The original testing on OSX used a variety of valid and invalid values for 'file' in --nethackrc=file and worked as intended, so the memory access bug wasn't noticed at that time.

Documentation may catch up someday, but unless you check nethack's relatively useless man page rather than the Guidebook you wouldn't find anything anyway.

"Access denied" is what you'll get when the specified file doesn't exist as well as when it exists but has permissions which don't allow you to access it.  If I remember correctly, avoiding "no such file" feedback is deliberate to prevent someone from using a nethack suid or sgid installation to probe the filesystem.  It doesn't switch to alternate code for more user-friendly feedback when there is no suid or sgid involved.
