### ISSUE TITLE
Elbereth not under hero is not effective despite dev's apparent intent

### ISSUE THREAD

**Issue by vultur-cadens** [NetHack/NetHack#900]
In https://github.com/NetHack/NetHack/commit/c2894a422b217d3fb8dd676f03ce2a35a3488e48, PatR put tins of spinach in the Monk locate level and also an Elbereth under the tins, with the comment "make a modest effort (Elbereth only) to prevent xorns from eating the tins".

I think this Elbereth does not actually do anything.  For a long time now (since 22ffe3b84e8a946966ca3b0e7a3666e4e6173a00), Elbereth has not worked when the hero is not standing on it.

In f0c73949689ac47db37e1290cd61c94cdf7ef8ba, PatR made monsters not be placed on scroll of scare monster or Elbereth in most cases unless there is no other choice, which makes me think that PatR believes that Elbereth is supposed to work when the hero is not standing on it.  But supposing that PatR knew that Elbereth was only supposed to work when the hero stands on it and the Elbereth case in `goodpos_onscary()` was just intended to provide an easy way to control monster locations, and the intent in the recent spinach commit was to prevent xorns from being created directly on the tins (even though they can still move onto the Elbereth square and eat the tins), this does not work as intended either, because `goodpos()` returns `TRUE` in the case of xorns before checking for scary, so xorns and elementals can spawn directly on scroll of scare monster and Elbereth anyway:
https://github.com/NetHack/NetHack/blob/c2894a422b217d3fb8dd676f03ce2a35a3488e48/src/teleport.c#L151-L158

Incidentally, the Elbereths under the sokoban and castle prizes are also practically useless except as a way to teach unspoiled new players about Elbereth engravings.

**Comment by copperwater** [comment]
Noting this comment in @pat-rankin's commit message: 

    This ought to be replaced by something more general.  Perhaps a new engraving type not usable by the player?

The natural way that I see this going is a wards system like in dNetHack (but with some heavy simplification). It neatly solves a number of problems with Elbereth:

* Removes another player/character knowledge problem. No longer a secret cheat code that a player in the know can use from the beginning, the character is only capable of using wards they have learned in-game.
* Instead of just one type of universally protective engraving, there can be multiple types of wards that serve different purposes. For instance, one ward could serve to protect items on the square it's engraved on, suitable to replace the Elbereths mentioned in this issue, but be useless at preventing attacks when the hero is standing on it. Other wards could scare off various subsets of monsters, addressing the problem that Elbereth can be used to get out of nearly any fight.
* Gets rid of the heavy emphasis on learning to use Elbereth as part of any new (spoiled) player's introduction to the game.

I've previously outlined a proposal for a wards system in vanilla (which I'm not happy with all the fine details of nowadays, but support the general idea), so if this is of any interest to the devteam, I can work on making a patch that would implement it.
