### ISSUE TITLE
Repeating travel with ^A has weird results

### ISSUE THREAD

**Issue by entrez** [NetHack/NetHack#905]
Repeating #travel with ^A repeats not just the travel command but also 
the specific keys the player entered to select the destination spot.  
Since the destination selection cursor starts at the previously selected 
destination <travelcc.x, travelcc.y> by default, those keys will 
actually change the selected destination so that it becomes different 
from the original one the player intended.  (Even if it started out at 
the player's position, that will have changed too given their last 
command was #travel.)  It will get further and further off every time 
they press ^A, until it gets stuck against the edge of the map 
somewhere.

Maybe dotravel should somehow override the command queue so that it 
actually stores dotravel_target as the extcmd.  I think that would 
mean ^A will actually resume traveling to the original intended spot, if 
that's what's desired for the combination of ^A and #travel.

**Comment by pat-rankin** [comment]
That should be fixed, but you can repeat travel to the previous destination with '#retravel' (default key \^\_).  That resumes traveling without having to specify the destination.

I think the proper fix is to just remember '#travel' without its destination, so ^A would prompt for a new target location.  Since that new target would default to the previous one, it wouldn't become particularly onerous for anyone not familiar with #retravel.

**Comment by entrez** [comment]
Yeah, I was telling someone about #retravel on #nethack a couple days ago and they said "oh, I see ^A does the same thing after being interrupted, so that's more convenient".  I didn't realize it worked like that now, I thought it still was just like entering #travel manually.

Remembering the keys for selecting the destination is the same with other commands that prompt for a location too, like ';' with ^A will just tell you about the same spot instead of reprompting you.  #travel + ^A working like #retravel I can see being convenient for people who don't want to learn another key binding, but that one seems definitely odd.
