### ISSUE TITLE
Lit room tiles are black in Windows Graphical Interface

### ISSUE THREAD

**Issue by StackC00ki3** [NetHack/NetHack#929]
![bug](https://user-images.githubusercontent.com/60530949/202855872-68e1db16-02e8-4486-bed2-857eb69f131f.png)

Steps to reproduce:
1. Launch NethackW.exe
2. Start a game

Version: 3.7-dev on Windows 10

Expected behavior: Lit room tiles are not filled with black

**Comment by pat-rankin** [comment]
You haven't indicated which version of nethack nor which version of Windows.  Either or both of those might matter.

I tried nethack 3.6.5 on Windows 11 and the background for room tiles (also open door tiles) is the same color as it is for corridor tiles when the room floor is visible.  The background is darker but still greenish like the bottom far right of your screen shot when not visible and remembered as lit.  I'm fairly sure that it looked the same when that machine was running Windows 10.

(I don't develop, maintain, or even play nethack on Windows which is why I don't have an up to date nethack on that system.  I'd be very surprised if 3.6.6 looked any different than 3.6.5.  I have never tried to-be-3.7, aka 3.7-dev, on any version of Windows.)

**Comment by StackC00ki3** [comment]
The version is 3.7-dev on Windows 10

**Comment by AnsonKindred** [comment]
I was able to "fix" this by modifying the paintTile method to draw foreground tiles via StretchBlt instead of lpfnTransparentBlt but I doubt that is a proper fix since the transparency gets lost. I assume there's something up with the bkmap and bkglyph in those cases that is causing it to be black instead of the normal room floor color, but I don't know enough about the code to know where that would be going wrong.

**Comment by nhmall** [comment]
There is a function in display.c called get_bk_glyph() that returns a default value of GLYPH_UNEXPLORED in 3.7, if that function doesn't determine there's something more appropriate to return as a background.  GLYPH_UNEXPLORED is mapped to a tile with all-black pixels, and that's what the Windows Graphical Interface was using as a background.

As of 5ac96e9, it treats GLYPH_UNEXPLORED the same way it treats NO_GLYPH, and doesn't treat it as a backgound.

**Comment by AnsonKindred** [comment]
Awesome. Thanks @nhmall, for the fix and the explanation.
