### ISSUE TITLE
Scroll of earth messages mention a “ceiling” even when there isn’t one

### ISSUE THREAD

**Issue by loggersviii** [NetHack/NetHack#954]
When read, the scroll of earth produces the message “the ceiling rumbles around you” (or something to that effect), and normally this works because the vast majority of the game is spent with a ceiling over your head, in the dungeon or elsewhere. But it also does this on the quest home levels. Unless the quest leaders and monsters live a uniquely subterranean lifestyle, this message does not make sense on many of the quest home levels. Many of these are outright stated to be outside in the fresh air; as such, I believe the scroll of earth’s current message in those locations is incorrect.

**Comment by pat-rankin** [comment]
There's a routine that is used to check for whether a level has a ceiling, and it returns 'no' for the planes of air and water but yes for everything else.  It has a comment, "[what about level 1 of the quest?]".

The home level is tricky, because being inside a building should probably be treated as 'yes' rather than have quest home levels yield a blanket 'no'.  The amount of effort to do that and get it right is probably not worth attempting.

For extra complication, the scroll reading code treats the Plane of Fire and the Astral Plane as not having a ceiling.  I'm not sure whether that is correct (they both clearly have floors so Fire isn't all fire, and Astral has rooms and corridors so ceiling would be expected to go along with them).  [If it is correct, the testing for those should be moved from there to the has_ceiling() routine.]

**Comment by entrez** [comment]
> The home level is tricky, because being inside a building should probably be treated as 'yes' rather than have quest home levels yield a blanket 'no'. The amount of effort to do that and get it right is probably not worth attempting.

xNetHack currently has home levels as a blanket "no ceiling" but this could change with https://github.com/copperwater/xNetHack/pull/86...

**Comment by lynn** [comment]
A far simpler solution is to reword the relevant messages so that they assume neither the presence or absence of a ceiling. "An avalanche of boulders materializes above you!"
