### ISSUE TITLE
Trapped monster can muse polytrap, causing impossible.

### ISSUE THREAD

**Issue by elunna** [NetHack/NetHack#972]
Found while fuzzing Hack'EM (https://github.com/elunna/hackem/issues/197)

A monster that is capable of muse-ing a polytrap can jump into a polytrap while trapped in a web (or potentially other traps).
Causes this panic: "trapped without a trap (fmon)"

Steps to reproduce:
Create a row of webs, then a row of poly traps next to each other. 
Then generate a leprechaun and lead it to the web,
It will jump onto the polytrap while still trapped.

I didn't have the build with sanity_check on, but I was able to probe the new monster with a wand of probing and it still said "trapped" after polymorphing.

**Comment by entrez** [comment]
I guess something like this would be enough to fix this, unless `mtrapped` can be set in some circumstances where the monster is still mobile?  (Oh, I see you already had applied part of this to your variant -- the patch in this comment also applies the `!mtrapped` condition to the similar "jump into a hole/trap door/etc" logic)

```diff
diff --git a/src/muse.c b/src/muse.c
index 3277efef7..097c965c6 100644
--- a/src/muse.c
+++ b/src/muse.c
@@ -470,7 +470,7 @@ find_defensive(struct monst* mtmp, boolean tryescape)
         }
     }
 
-    if (stuck || immobile) {
+    if (stuck || immobile || mtmp->mtrapped) {
         ; /* fleeing by stairs or traps is not possible */
     } else if (levl[x][y].typ == STAIRS) {
         stway = stairway_at(x,y);
@@ -1907,7 +1907,7 @@ find_misc(struct monst* mtmp)
     if (dist2(x, y, mtmp->mux, mtmp->muy) > 36)
         return FALSE;
 
-    if (!stuck && !immobile && (mtmp->cham == NON_PM)
+    if (!stuck && !immobile && !mtmp->mtrapped && (mtmp->cham == NON_PM)
         && mons[(pmidx = monsndx(mdat))].difficulty < 6) {
         boolean ignore_boulders = (verysmall(mdat) || throws_rocks(mdat)
                                    || passes_walls(mdat)),
```

By the way, that error is an impossible, not a panic, and even when I reproduce this scenario it isn't triggered for me (because the monster ends up sitting on the polytrap, so the "`mtrapped` is set but there's no trap at those coordinates" condition isn't met).

**Comment by pat-rankin** [comment]
The debug-fuzzer (code that generates random command keystrokes so that the game can be set to play by itself until it eventually crashes for some reason) escalates all impossible() calls to panic().

**Comment by elunna** [comment]
Ah sorry for any confusion, I was getting an impossible running the fuzzer for Hack'EM
