### ISSUE TITLE
[3.7.0-66] can see scroll labeling while blind

### ISSUE THREAD

**Issue by jeremyhetzler** [NetHack/NetHack#986]
```
The yellow light explodes!  You are blinded by a blast of light!
You hear someone reading a scroll labeled VELOX NEB.

Unix NetHack Version 3.7.0-66 Work-in-progress - last build Dec 26 2022 00:49:01 (55254d10815e23f0e7c0ebc937178fe17f3ffff8,branch:master).
```

While blind, player should not be able to see the labeling on a scroll.

**Comment by entrez** [comment]
I've always figured reading the scroll typically involves reading the label out loud in some way.  If that's how it works I don't think there's any contradiction in getting the message "you hear someone reading a scroll labeled VELOX NEB" while blinded, since it only involves hearing the monster say "VELOX NEB".

**Comment by chappg** [comment]
"You hear incantations of VELOX NEB" may be less awkward of a wording
