### ISSUE TITLE
[3.7.0-66] during text entry, arrow keys produce hjkl

### ISSUE THREAD

**Issue by jeremyhetzler** [NetHack/NetHack#987]
```
Unix NetHack Version 3.7.0-66 Work-in-progress - last build Dec 26 2022 00:49:01
(55254d10815e23f0e7c0ebc937178fe17f3ffff8,branch:master).
```
During text entry, arrow keys produce hjkl. For example, in #call or /? .

Arrow keys work correctly when used to move on the map.

Option number_pad is set to 0.

Left and right arrow keys should move the text entry cursor left and right. Up and down arrow keys should do nothing.

**Comment by pat-rankin** [comment]
> During text entry, arrow keys produce hjkl. For example, in #call or /? .
> Arrow keys work correctly when used to move on the map.

Whether or not that happens is interface-dependent.  Presumably you're using curses because tty doesn't do that, except on Windows.  X11 and Qt don't to that either.

> Left and right arrow keys should move the text entry cursor left and
> right. Up and down arrow keys should do nothing.

NetHack has never supported that.  The only text editing capabilities it handles is <delete> or <backspace> to remove the character to the left of the cursor and the kill-character (probably ^U) to remove the entire line.  Recent versions have changed how <escape> operates so that it behaves like ^U if you've typed something, only cancelling the whole action (traditional behavior) if used when there's nothing pending.

If you enabled number_pad, the arrows under curses will produce 4286 instead of hjkl.  It's trying to do you a favor rather than just reject the arrows outright.

**Comment by pat-rankin** [comment]
github comment composer strikes again, removing text that was enclosed by angle brackets.  "it handles is or to remove" was "it handles is /delete/ or /backspace/ to remove" in the first sentence of my second paragraph, and "changed how operates" was "changed how /escape/ operates" in the second sentence.

**Comment by jeremyhetzler** [comment]
Thanks Pat.

I am using curses.

I think if arrow keys would do nothing during text entry, that would be an
improvement. The current behavior is odd and surprising.

Just my two cents.

Thanks,
Jeremy
