### ISSUE TITLE
[3.7-73] Truncated message encountered in game window

### ISSUE THREAD

**Issue by chappg** [NetHack/NetHack#990]
I encountered the following truncated message in the game window:

"The spell hits the dwarf!  You kill the dwarf!  Welcome to experience level"

The game log correctly shows "Welcome to experience level 6", so it appears the display string was truncated for some reason.

Game Settings:  130x30 in terminal with curses and 2 status lines in the game options
Version: 3.7.0-73

**Comment by entrez** [comment]
Did you have a MSGTYPE=stop on the "welcome to experience level" message?  And perm_invent enabled?

**Comment by chappg** [comment]
Good question- I do not have that specific stop msg configured nor on the nearby messages, but I do have others set on potentially deadly conditions:

https://www.hardfought.org/userdata/a/a1/nethack/a1.nhrc

And yes, perm_invent is enabled.

**Comment by pat-rankin** [comment]
Level gain and level loss were recently changed to force --More-- (or >> for curses) so that sound effects for those two events have time to play, so they have an  implicit MSGTYPE:stop now.  (The new pause doesn't depend upon whether sound effects are actually enabled.)

I'm not sure if that was a good idea, but without it #levelchange in wizard mode played the loss effect just once even when dropping multiple levels.  (That behavior might depend on audio hardware.)  For tty, the gain effect was already getting played once per increment due to the more verbose messaging it has.  But that probably wouldn't be the case for a multi-line message window for other interfaces.  (It's not something that comes up in normal play because the change only goes up or down by 1 level at a time.)

**Comment by entrez** [comment]
Seems like this would have fulfilled all the criteria to trigger the #993 issue then, can't say with absolute certainty but I feel pretty sure that must be it.

**Comment by chappg** [comment]
I believe the pull request will fix the issue. I received a 'More' prompt which I immediately ack'd before writing down the bug. Thank you!!!

**Comment by vultur-cadens** [comment]
> I'm not sure if that was a good idea, but without it #levelchange in wizard mode played the loss effect just once even when dropping multiple levels. (That behavior might depend on audio hardware.) For tty, the gain effect was already getting played once per increment due to the more verbose messaging it has. But that probably wouldn't be the case for a multi-line message window for other interfaces. (It's not something that comes up in normal play because the change only goes up or down by 1 level at a time.)

This is kind of annoying in wizard mode because you can't skip all of the level change messages with a single press of ESC anymore (using tty).  It's only wizard mode though.

For some cases of "normal play", it might still come up because blessed potion of restore ability can restore multiple levels at once.  People who deliberately drain to level 1 and then restore to level 15-ish might notice (either that they are forced to hear 14 level gain sounds or that they don't hear 14 level gain sounds, depending on which behavior is implemented).
